/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import com.alogram.payrisk.v1.models.Account
import com.alogram.payrisk.v1.models.EntityIds
import com.alogram.payrisk.v1.models.Interaction

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param eventSubtype The specific subtype of the account event (e.g., 'signup', 'login').
 * @param entities 
 * @param account 
 * @param interaction 
 */


data class AccountCheckRequest (

    /* The specific subtype of the account event (e.g., 'signup', 'login'). */
    @Json(name = "eventSubtype")
    val eventSubtype: AccountCheckRequest.EventSubtype,

    @Json(name = "entities")
    val entities: EntityIds? = null,

    @Json(name = "account")
    val account: Account? = null,

    @Json(name = "interaction")
    val interaction: Interaction? = null

) {

    /**
     * The specific subtype of the account event (e.g., 'signup', 'login').
     *
     * Values: SIGNUP,LOGIN,PASSWORD_RESET,MFA_RESET,SETTING_CHANGE
     */
    @JsonClass(generateAdapter = false)
    enum class EventSubtype(val value: kotlin.String) {
        @Json(name = "signup") SIGNUP("signup"),
        @Json(name = "login") LOGIN("login"),
        @Json(name = "password_reset") PASSWORD_RESET("password_reset"),
        @Json(name = "mfa_reset") MFA_RESET("mfa_reset"),
        @Json(name = "setting_change") SETTING_CHANGE("setting_change");
    }

}
