/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import com.alogram.payrisk.v1.models.DeviceInfo

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The application-layer Account object.
 *
 * @param deviceInfo 
 * @param timestamp RFC 3339 timestamp with timezone.
 * @param phone Phone number that supports international E.164 format, as well as spaces, dashes, and parentheses.  Examples: \"+1 (415) 555-2671\", \"415-555-2671\", \"+14155552671\" 
 * @param email Email address of the customer.
 * @param metadata Optional key-value pairs providing additional context for the request.  Each key should be descriptive, and values should not exceed 2048 characters.  Each key should be descriptive. 
 */


data class Account (

    @Json(name = "deviceInfo")
    val deviceInfo: DeviceInfo? = null,

    /* RFC 3339 timestamp with timezone. */
    @Json(name = "timestamp")
    val timestamp: kotlin.String? = null,

    /* Phone number that supports international E.164 format, as well as spaces, dashes, and parentheses.  Examples: \"+1 (415) 555-2671\", \"415-555-2671\", \"+14155552671\"  */
    @Json(name = "phone")
    val phone: kotlin.String? = null,

    /* Email address of the customer. */
    @Json(name = "email")
    val email: kotlin.String? = null,

    /* Optional key-value pairs providing additional context for the request.  Each key should be descriptive, and values should not exceed 2048 characters.  Each key should be descriptive.  */
    @Json(name = "metadata")
    val metadata: kotlin.String? = null

) {


}
