/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * AVS response codes: Y: Address and 5-digit ZIP match N: Address and 5-digit ZIP do not match A: Address matches, ZIP does not Z: ZIP matches, address does not U: Address unavailable R: System unavailable S: Not supported G: Global non-AVS B: International AVS C: Street address and postal code not verified due to incompatible formats D: Street address and postal code not verified due to incompatible formats M: Street address and postal code match P: Street address not verified. Postal code matches. X: Street address and 9-digit ZIP match W: Street address not verified. 9-digit ZIP matches. 
 *
 * Values: Y,N,A,Z,U,R,S,G,B,C,D,M,P,X,W
 */

@JsonClass(generateAdapter = false)
enum class AvsResultEnum(val value: kotlin.String) {

    @Json(name = "Y")
    Y("Y"),

    @Json(name = "N")
    N("N"),

    @Json(name = "A")
    A("A"),

    @Json(name = "Z")
    Z("Z"),

    @Json(name = "U")
    U("U"),

    @Json(name = "R")
    R("R"),

    @Json(name = "S")
    S("S"),

    @Json(name = "G")
    G("G"),

    @Json(name = "B")
    B("B"),

    @Json(name = "C")
    C("C"),

    @Json(name = "D")
    D("D"),

    @Json(name = "M")
    M("M"),

    @Json(name = "P")
    P("P"),

    @Json(name = "X")
    X("X"),

    @Json(name = "W")
    W("W");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is AvsResultEnum) "$data" else null

        /**
         * Returns a valid [AvsResultEnum] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): AvsResultEnum? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}
