/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type Fixed to `bank_transfer` for this schema.
 */


data class BankTransfer (

    /* Fixed to `bank_transfer` for this schema. */
    @Json(name = "type")
    val type: BankTransfer.Type

) {

    /**
     * Fixed to `bank_transfer` for this schema.
     *
     * Values: BANK_TRANSFER
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "bank_transfer") BANK_TRANSFER("bank_transfer");
    }

}
