/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import com.alogram.payrisk.v1.models.AvsResultEnum
import com.alogram.payrisk.v1.models.CardNetworkEnum
import com.alogram.payrisk.v1.models.CvvResultEnum
import com.alogram.payrisk.v1.models.PaymentCardTypeEnum
import com.alogram.payrisk.v1.models.ScaMethodEnum
import com.alogram.payrisk.v1.models.ThreeDSData

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type Fixed to `card` for this schema.
 * @param cardNetwork 
 * @param cardType 
 * @param bin Bank Identification Number (IIN). First 6–8 digits of the PAN; do not send full PAN.
 * @param issuerCountry ISO 3166-1 alpha-2 country code.
 * @param avsResult 
 * @param cvvResult 
 * @param scaMethod 
 * @param threeDS 
 */


data class Card (

    /* Fixed to `card` for this schema. */
    @Json(name = "type")
    val type: Card.Type,

    @Json(name = "cardNetwork")
    val cardNetwork: CardNetworkEnum? = null,

    @Json(name = "cardType")
    val cardType: PaymentCardTypeEnum? = null,

    /* Bank Identification Number (IIN). First 6–8 digits of the PAN; do not send full PAN. */
    @Json(name = "bin")
    val bin: kotlin.String? = null,

    /* ISO 3166-1 alpha-2 country code. */
    @Json(name = "issuerCountry")
    val issuerCountry: kotlin.String? = null,

    @Json(name = "avsResult")
    val avsResult: AvsResultEnum? = null,

    @Json(name = "cvvResult")
    val cvvResult: CvvResultEnum? = null,

    @Json(name = "scaMethod")
    val scaMethod: ScaMethodEnum? = null,

    @Json(name = "threeDS")
    val threeDS: ThreeDSData? = null

) {

    /**
     * Fixed to `card` for this schema.
     *
     * Values: CARD
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "card") CARD("card");
    }

}
