/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import com.alogram.payrisk.v1.models.RiskLevelEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Risk analysis for a specific business category.
 *
 * @param level 
 * @param score Category-specific risk score (0.00 - 1.00).
 * @param reasons Specific reason codes for this category.
 */


data class CategorySignal (

    @Json(name = "level")
    val level: RiskLevelEnum,

    /* Category-specific risk score (0.00 - 1.00). */
    @Json(name = "score")
    val score: kotlin.Float? = null,

    /* Specific reason codes for this category. */
    @Json(name = "reasons")
    val reasons: kotlin.collections.List<kotlin.String>? = null

) {


}
