/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * pos: 'Point of Sale', ecom: 'E-commerce', in_app: 'In-App Purchase', ivr: 'Interactive Voice Response'. 
 *
 * Values: POS,ECOM,IN_APP,IVR
 */

@JsonClass(generateAdapter = false)
enum class ChannelEnum(val value: kotlin.String) {

    @Json(name = "pos")
    POS("pos"),

    @Json(name = "ecom")
    ECOM("ecom"),

    @Json(name = "in_app")
    IN_APP("in_app"),

    @Json(name = "ivr")
    IVR("ivr");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ChannelEnum) "$data" else null

        /**
         * Returns a valid [ChannelEnum] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ChannelEnum? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}
