/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import com.alogram.payrisk.v1.models.EntityIds
import com.alogram.payrisk.v1.models.Identity
import com.alogram.payrisk.v1.models.Purchase

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Request for synchronous purchase risk check.
 *
 * @param entities 
 * @param purchase 
 * @param eventType (optional) event being checked, this may expand later beyond 'purchase'.
 * @param paymentIntentId Server-minted unique payment identifier.
 * @param identity 
 */


data class CheckRequest (

    @Json(name = "entities")
    val entities: EntityIds,

    @Json(name = "purchase")
    val purchase: Purchase,

    /* (optional) event being checked, this may expand later beyond 'purchase'. */
    @Json(name = "eventType")
    val eventType: CheckRequest.EventType? = EventType.PURCHASE,

    /* Server-minted unique payment identifier. */
    @Json(name = "paymentIntentId")
    val paymentIntentId: kotlin.String? = null,

    @Json(name = "identity")
    val identity: Identity? = null

) {

    /**
     * (optional) event being checked, this may expand later beyond 'purchase'.
     *
     * Values: PURCHASE
     */
    @JsonClass(generateAdapter = false)
    enum class EventType(val value: kotlin.String) {
        @Json(name = "purchase") PURCHASE("purchase");
    }

}
