/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * M: CVV match N: CVV no match P: Not processed S: Should have been present U: Unavailable 
 *
 * Values: M,N,P,S,U
 */

@JsonClass(generateAdapter = false)
enum class CvvResultEnum(val value: kotlin.String) {

    @Json(name = "M")
    M("M"),

    @Json(name = "N")
    N("N"),

    @Json(name = "P")
    P("P"),

    @Json(name = "S")
    S("S"),

    @Json(name = "U")
    U("U");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is CvvResultEnum) "$data" else null

        /**
         * Returns a valid [CvvResultEnum] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): CvvResultEnum? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}
