/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import com.alogram.payrisk.v1.models.FraudScore
import com.alogram.payrisk.v1.models.ReasonDetail
import com.alogram.payrisk.v1.models.RiskBreakdown

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The synchronous risk decision for a purchase.
 *
 * @param assessmentId Universal decision identifier. For purchases, equals paymentIntentId.
 * @param decision 
 * @param decisionAt RFC 3339 timestamp with timezone.
 * @param riskScore 
 * @param fraudScore 
 * @param breakdown 
 * @param reasonCodes Technical reason codes for the decision.
 * @param reasons Structured reason details for the decision.
 * @param actions 
 * @param paymentIntentId Server-minted unique payment identifier.
 * @param policyVersion The version of the policy that generated the decision.
 * @param modelVersion The version of the model that generated the decision.
 * @param ttlSeconds Time to live for the decision in seconds.
 */


data class DecisionResponse (

    /* Universal decision identifier. For purchases, equals paymentIntentId. */
    @Json(name = "assessmentId")
    val assessmentId: kotlin.String,

    @Json(name = "decision")
    val decision: DecisionResponse.Decision,

    /* RFC 3339 timestamp with timezone. */
    @Json(name = "decisionAt")
    val decisionAt: kotlin.String,

    @Json(name = "riskScore")
    val riskScore: kotlin.Float,

    @Json(name = "fraudScore")
    val fraudScore: FraudScore? = null,

    @Json(name = "breakdown")
    val breakdown: RiskBreakdown? = null,

    /* Technical reason codes for the decision. */
    @Json(name = "reasonCodes")
    val reasonCodes: kotlin.collections.List<kotlin.String>? = null,

    /* Structured reason details for the decision. */
    @Json(name = "reasons")
    val reasons: kotlin.collections.List<ReasonDetail>? = null,

    @Json(name = "actions")
    val actions: kotlin.collections.List<DecisionResponse.Actions>? = null,

    /* Server-minted unique payment identifier. */
    @Json(name = "paymentIntentId")
    val paymentIntentId: kotlin.String? = null,

    /* The version of the policy that generated the decision. */
    @Json(name = "policyVersion")
    val policyVersion: kotlin.String? = null,

    /* The version of the model that generated the decision. */
    @Json(name = "modelVersion")
    val modelVersion: kotlin.String? = null,

    /* Time to live for the decision in seconds. */
    @Json(name = "ttlSeconds")
    val ttlSeconds: kotlin.Int? = null

) {

    /**
     * 
     *
     * Values: APPROVE,REVIEW,DECLINE,STEP_UP
     */
    @JsonClass(generateAdapter = false)
    enum class Decision(val value: kotlin.String) {
        @Json(name = "approve") APPROVE("approve"),
        @Json(name = "review") REVIEW("review"),
        @Json(name = "decline") DECLINE("decline"),
        @Json(name = "step_up") STEP_UP("step_up");
    }
    /**
     * 
     *
     * Values: STEP_UP,THROTTLE,LOCK_ACCOUNT,DECLINE,QUEUE_REVIEW
     */
    @JsonClass(generateAdapter = false)
    enum class Actions(val value: kotlin.String) {
        @Json(name = "step_up") STEP_UP("step_up"),
        @Json(name = "throttle") THROTTLE("throttle"),
        @Json(name = "lock_account") LOCK_ACCOUNT("lock_account"),
        @Json(name = "decline") DECLINE("decline"),
        @Json(name = "queue_review") QUEUE_REVIEW("queue_review");
    }

}
