/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import com.alogram.payrisk.v1.models.Integrity
import com.alogram.payrisk.v1.models.IpInfo

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Aggregated device fingerprinting and behavioral patterns used for fraud detection.
 *
 * @param fingerprint Unique hash representing the device's fingerprint. Lowercase hex. Prefix \"fp_\". 
 * @param userAgent Browser's User-Agent string, useful for identifying OS and browser type.  Must be between 10 and 512 printable ASCII characters. 
 * @param ip 
 * @param integrity 
 */


data class DeviceInfo (

    /* Unique hash representing the device's fingerprint. Lowercase hex. Prefix \"fp_\".  */
    @Json(name = "fingerprint")
    val fingerprint: kotlin.String? = null,

    /* Browser's User-Agent string, useful for identifying OS and browser type.  Must be between 10 and 512 printable ASCII characters.  */
    @Json(name = "userAgent")
    val userAgent: kotlin.String? = null,

    @Json(name = "ip")
    val ip: IpInfo? = null,

    @Json(name = "integrity")
    val integrity: Integrity? = null

) {


}
