/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Canonical entity identifiers (tenant/client/user/device/session). Do not send raw PII. Hash emails/phones/addresses as sha256 and prefix with 'sha256_'. Tiered support:   - tenantId is the top-level SaaS customer (required for all flows).   - clientId is the tenant’s downstream business customer (e.g. merchant/partner) and MAY be omitted for     processor / bank / PSP-style integrations.   - endCustomerId is the tenant/client’s consumer or business account (cardholder, shopper, etc.) and     MAY be omitted for purely device- or instrument-level checks. 
 *
 * @param tenantId Canonical ID for the paying organization (Tenant). Opaque, immutable, lowercase.  Must start with \"tid_\". Do not use domains or emails here. For a tenant's domain,  use a separate field (e.g., tenantDomain). 
 * @param clientId Canonical ID for the Tenant’s business customer (e.g., merchant/partner).  Opaque, immutable, lowercase. Must start with 'cid_'. 
 * @param endCustomerId Canonical ID for the client’s end user / consumer (account holder).  Opaque, immutable, lowercase. Must start with \"ecid_\".  Do not put PII (like emails or phone numbers) in this field. 
 * @param memberId Canonical ID for a Tenant member/operator (employee/contractor) using the platform.  Opaque, immutable, lowercase. Must start with 'mid_'. 
 * @param paymentInstrumentId Tokenized instrument ID (non-PCI).
 * @param deviceId Server-issued stable device token (device-level identifier). Should persist across sessions and logins on the same browser/device. 
 * @param sessionId Application/user session identifier (login or checkout session). Typically rotates more frequently than deviceId and may be tied to authentication. 
 * @param emailHash Normalized+lowercased email hash (e.g., sha256).
 * @param emailDomainHash Normalized+lowercased email *domain* hash (e.g., sha256).
 * @param phoneHash Normalized+lowercased phone hash (e.g., sha256).
 * @param shippingAddressHash Normalized+lowercased shipping address hash (e.g., sha256).
 * @param billingAddressHash Normalized+lowercased billing address hash (e.g., sha256).
 */


data class EntityIds (

    /* Canonical ID for the paying organization (Tenant). Opaque, immutable, lowercase.  Must start with \"tid_\". Do not use domains or emails here. For a tenant's domain,  use a separate field (e.g., tenantDomain).  */
    @Json(name = "tenantId")
    val tenantId: kotlin.String? = null,

    /* Canonical ID for the Tenant’s business customer (e.g., merchant/partner).  Opaque, immutable, lowercase. Must start with 'cid_'.  */
    @Json(name = "clientId")
    val clientId: kotlin.String? = null,

    /* Canonical ID for the client’s end user / consumer (account holder).  Opaque, immutable, lowercase. Must start with \"ecid_\".  Do not put PII (like emails or phone numbers) in this field.  */
    @Json(name = "endCustomerId")
    val endCustomerId: kotlin.String? = null,

    /* Canonical ID for a Tenant member/operator (employee/contractor) using the platform.  Opaque, immutable, lowercase. Must start with 'mid_'.  */
    @Json(name = "memberId")
    val memberId: kotlin.String? = null,

    /* Tokenized instrument ID (non-PCI). */
    @Json(name = "paymentInstrumentId")
    val paymentInstrumentId: kotlin.String? = null,

    /* Server-issued stable device token (device-level identifier). Should persist across sessions and logins on the same browser/device.  */
    @Json(name = "deviceId")
    val deviceId: kotlin.String? = null,

    /* Application/user session identifier (login or checkout session). Typically rotates more frequently than deviceId and may be tied to authentication.  */
    @Json(name = "sessionId")
    val sessionId: kotlin.String? = null,

    /* Normalized+lowercased email hash (e.g., sha256). */
    @Json(name = "emailHash")
    val emailHash: kotlin.String? = null,

    /* Normalized+lowercased email *domain* hash (e.g., sha256). */
    @Json(name = "emailDomainHash")
    val emailDomainHash: kotlin.String? = null,

    /* Normalized+lowercased phone hash (e.g., sha256). */
    @Json(name = "phoneHash")
    val phoneHash: kotlin.String? = null,

    /* Normalized+lowercased shipping address hash (e.g., sha256). */
    @Json(name = "shippingAddressHash")
    val shippingAddressHash: kotlin.String? = null,

    /* Normalized+lowercased billing address hash (e.g., sha256). */
    @Json(name = "billingAddressHash")
    val billingAddressHash: kotlin.String? = null

) {


}
