/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The method used to capture card data.
 *
 * Values: CHIP,CONTACTLESS,MAGSTRIPE,MANUAL_KEYED,CARD_ON_FILE,WALLET_TOKEN,NETWORK_TOKEN
 */

@JsonClass(generateAdapter = false)
enum class EntryMethodEnum(val value: kotlin.String) {

    @Json(name = "chip")
    CHIP("chip"),

    @Json(name = "contactless")
    CONTACTLESS("contactless"),

    @Json(name = "magstripe")
    MAGSTRIPE("magstripe"),

    @Json(name = "manual_keyed")
    MANUAL_KEYED("manual_keyed"),

    @Json(name = "card_on_file")
    CARD_ON_FILE("card_on_file"),

    @Json(name = "wallet_token")
    WALLET_TOKEN("wallet_token"),

    @Json(name = "network_token")
    NETWORK_TOKEN("network_token");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is EntryMethodEnum) "$data" else null

        /**
         * Returns a valid [EntryMethodEnum] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): EntryMethodEnum? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}
