/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import com.alogram.payrisk.v1.models.ConfidenceEnum
import com.alogram.payrisk.v1.models.RiskLevelEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Fraud score for a specific transaction or entity.
 *
 * @param riskLevel 
 * @param confidence 
 * @param score Fraud risk score (0.00 - 1.00).
 * @param explanation A human-readable explanation of the fraud score, if available.
 */


data class FraudScore (

    @Json(name = "riskLevel")
    val riskLevel: RiskLevelEnum,

    @Json(name = "confidence")
    val confidence: ConfidenceEnum? = null,

    /* Fraud risk score (0.00 - 1.00). */
    @Json(name = "score")
    val score: kotlin.Float? = null,

    /* A human-readable explanation of the fraud score, if available. */
    @Json(name = "explanation")
    val explanation: kotlin.String? = null

) {


}
