/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import com.alogram.payrisk.v1.models.PostalAddress

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Optional raw identity details for the account associated with the purchase. These fields (email, phone, addresses) are used for normalization, hashing, and risk feature extraction (e.g., email/phone/domain scoring, address risk), and are not stored in raw form by Alogram.  When provided, Alogram will derive and/or cross-check: - emailHash / phoneHash / shippingAddressHash / billingAddressHash   in the internal entity model - email/phone/domain risk signals - address consistency and geo-distance checks 
 *
 * @param email Email address of the customer.
 * @param emailDomain Email domain only (no local part). Useful for domain-level risk and allow/deny lists without sending full email PII. Example: \"gmail.com\", \"merchant-example.co.uk\" 
 * @param phone Phone number that supports international E.164 format, as well as spaces, dashes, and parentheses.  Examples: \"+1 (415) 555-2671\", \"415-555-2671\", \"+14155552671\" 
 * @param shippingAddress 
 * @param billingAddress 
 */


data class Identity (

    /* Email address of the customer. */
    @Json(name = "email")
    val email: kotlin.String? = null,

    /* Email domain only (no local part). Useful for domain-level risk and allow/deny lists without sending full email PII. Example: \"gmail.com\", \"merchant-example.co.uk\"  */
    @Json(name = "emailDomain")
    val emailDomain: kotlin.String? = null,

    /* Phone number that supports international E.164 format, as well as spaces, dashes, and parentheses.  Examples: \"+1 (415) 555-2671\", \"415-555-2671\", \"+14155552671\"  */
    @Json(name = "phone")
    val phone: kotlin.String? = null,

    @Json(name = "shippingAddress")
    val shippingAddress: PostalAddress? = null,

    @Json(name = "billingAddress")
    val billingAddress: PostalAddress? = null

) {


}
