/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The type of interaction being recorded.
 *
 * Values: LOGIN,FEATURE_USE,SETTING_CHANGE,PAGE_VIEW,_3RD_PARTY_EVENT,CUSTOM_EVENT
 */

@JsonClass(generateAdapter = false)
enum class InteractionTypeEnum(val value: kotlin.String) {

    @Json(name = "login")
    LOGIN("login"),

    @Json(name = "feature_use")
    FEATURE_USE("feature_use"),

    @Json(name = "setting_change")
    SETTING_CHANGE("setting_change"),

    @Json(name = "page_view")
    PAGE_VIEW("page_view"),

    @Json(name = "3rd_party_event")
    _3RD_PARTY_EVENT("3rd_party_event"),

    @Json(name = "custom_event")
    CUSTOM_EVENT("custom_event");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is InteractionTypeEnum) "$data" else null

        /**
         * Returns a valid [InteractionTypeEnum] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): InteractionTypeEnum? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}
