/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import com.alogram.payrisk.v1.models.DeviceInfo
import com.alogram.payrisk.v1.models.InteractionTypeEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The application-layer Interaction object.
 *
 * @param interactionType 
 * @param locationId Unique identifier for the location where the transaction occurred.
 * @param deviceInfo 
 * @param timestamp RFC 3339 timestamp with timezone.
 * @param metadata Optional key-value pairs providing additional context for the request.  Each key should be descriptive, and values should not exceed 2048 characters.  Each key should be descriptive. 
 */


data class Interaction (

    @Json(name = "interactionType")
    val interactionType: InteractionTypeEnum,

    /* Unique identifier for the location where the transaction occurred. */
    @Json(name = "locationId")
    val locationId: kotlin.String? = null,

    @Json(name = "deviceInfo")
    val deviceInfo: DeviceInfo? = null,

    /* RFC 3339 timestamp with timezone. */
    @Json(name = "timestamp")
    val timestamp: kotlin.String? = null,

    /* Optional key-value pairs providing additional context for the request.  Each key should be descriptive, and values should not exceed 2048 characters.  Each key should be descriptive.  */
    @Json(name = "metadata")
    val metadata: kotlin.String? = null

) {


}
