/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param isProxyVpnTor Indicates whether the IP address is associated with a proxy, VPN, or Tor exit node. 
 * @param isHostingProvider Indicates whether the IP address belongs to a hosting provider (e.g., data center, cloud provider). 
 * @param isHeadless Indicates whether the browser is running in headless mode (e.g., automated testing, scraping). 
 * @param isAutomation Indicates whether the request originated from an automated script or bot. 
 * @param isEmulator Indicates whether the request originated from an emulator (e.g., Android Emulator, iOS Simulator). 
 * @param isRootedJailbroken Indicates whether the device is rooted (Android) or jailbroken (iOS). 
 */


data class Integrity (

    /* Indicates whether the IP address is associated with a proxy, VPN, or Tor exit node.  */
    @Json(name = "isProxyVpnTor")
    val isProxyVpnTor: kotlin.Boolean? = null,

    /* Indicates whether the IP address belongs to a hosting provider (e.g., data center, cloud provider).  */
    @Json(name = "isHostingProvider")
    val isHostingProvider: kotlin.Boolean? = null,

    /* Indicates whether the browser is running in headless mode (e.g., automated testing, scraping).  */
    @Json(name = "isHeadless")
    val isHeadless: kotlin.Boolean? = null,

    /* Indicates whether the request originated from an automated script or bot.  */
    @Json(name = "isAutomation")
    val isAutomation: kotlin.Boolean? = null,

    /* Indicates whether the request originated from an emulator (e.g., Android Emulator, iOS Simulator).  */
    @Json(name = "isEmulator")
    val isEmulator: kotlin.Boolean? = null,

    /* Indicates whether the device is rooted (Android) or jailbroken (iOS).  */
    @Json(name = "isRootedJailbroken")
    val isRootedJailbroken: kotlin.Boolean? = null

) {


}
