/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type Fixed to `invoice` for this schema.
 */


data class Invoice (

    /* Fixed to `invoice` for this schema. */
    @Json(name = "type")
    val type: Invoice.Type

) {

    /**
     * Fixed to `invoice` for this schema.
     *
     * Values: INVOICE
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "invoice") INVOICE("invoice");
    }

}
