/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param ipAddress IP address of the customer, client, or user that initiated the request. Each octet must be between 0 and 255. 
 * @param ipv6 IPv6 address.
 * @param ipVersion IP protocol version.
 * @param ipPrefix CIDR, e.g., 198.51.100.0/24 or 2001:db8::/48
 * @param asn Autonomous System Number (ASN) of the IP address.
 * @param org Organization associated with the IP address.
 * @param company Company associated with the IP address.
 * @param country ISO 3166-1 alpha-2 country code.
 * @param region Region associated with the IP address.
 * @param city City associated with the IP address.
 * @param postalCode Postal code associated with the IP address.
 */


data class IpInfo (

    /* IP address of the customer, client, or user that initiated the request. Each octet must be between 0 and 255.  */
    @Json(name = "ipAddress")
    val ipAddress: kotlin.String? = null,

    /* IPv6 address. */
    @Json(name = "ipv6")
    val ipv6: kotlin.String? = null,

    /* IP protocol version. */
    @Json(name = "ipVersion")
    val ipVersion: IpInfo.IpVersion? = IpVersion.IPV4,

    /* CIDR, e.g., 198.51.100.0/24 or 2001:db8::/48 */
    @Json(name = "ipPrefix")
    val ipPrefix: kotlin.String? = null,

    /* Autonomous System Number (ASN) of the IP address. */
    @Json(name = "asn")
    val asn: kotlin.String? = null,

    /* Organization associated with the IP address. */
    @Json(name = "org")
    val org: kotlin.String? = null,

    /* Company associated with the IP address. */
    @Json(name = "company")
    val company: kotlin.String? = null,

    /* ISO 3166-1 alpha-2 country code. */
    @Json(name = "country")
    val country: kotlin.String? = null,

    /* Region associated with the IP address. */
    @Json(name = "region")
    val region: kotlin.String? = null,

    /* City associated with the IP address. */
    @Json(name = "city")
    val city: kotlin.String? = null,

    /* Postal code associated with the IP address. */
    @Json(name = "postalCode")
    val postalCode: kotlin.String? = null

) {

    /**
     * IP protocol version.
     *
     * Values: IPV4,IPV6
     */
    @JsonClass(generateAdapter = false)
    enum class IpVersion(val value: kotlin.String) {
        @Json(name = "ipv4") IPV4("ipv4"),
        @Json(name = "ipv6") IPV6("ipv6");
    }

}
