/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import com.alogram.payrisk.v1.models.Account
import com.alogram.payrisk.v1.models.EntityIds
import com.alogram.payrisk.v1.models.KycPayload

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param eventSubtype The specific subtype of the KYC event.
 * @param account 
 * @param entities 
 * @param kyc 
 */


data class KycCheckRequest (

    /* The specific subtype of the KYC event. */
    @Json(name = "eventSubtype")
    val eventSubtype: KycCheckRequest.EventSubtype,

    @Json(name = "account")
    val account: Account,

    @Json(name = "entities")
    val entities: EntityIds? = null,

    @Json(name = "kyc")
    val kyc: KycPayload? = null

) {

    /**
     * The specific subtype of the KYC event.
     *
     * Values: PRE_KYC_CHECK,DOC_SCAN,LIVENESS,ADDRESS_CHECK,SANCTIONS_PEP
     */
    @JsonClass(generateAdapter = false)
    enum class EventSubtype(val value: kotlin.String) {
        @Json(name = "pre_kyc_check") PRE_KYC_CHECK("pre_kyc_check"),
        @Json(name = "doc_scan") DOC_SCAN("doc_scan"),
        @Json(name = "liveness") LIVENESS("liveness"),
        @Json(name = "address_check") ADDRESS_CHECK("address_check"),
        @Json(name = "sanctions_pep") SANCTIONS_PEP("sanctions_pep");
    }

}
