/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * KYC provider result payload.
 *
 * @param provider 
 * @param documentType The document type used for verification.
 * @param country 
 * @param result The result of the KYC check.
 * @param reasonCodes Array of reason codes for the KYC check.
 * @param metadata Optional key-value pairs providing additional context for the request.  Each key should be descriptive, and values should not exceed 2048 characters.  Each key should be descriptive. 
 */


data class KycPayload (

    @Json(name = "provider")
    val provider: kotlin.String? = null,

    /* The document type used for verification. */
    @Json(name = "documentType")
    val documentType: KycPayload.DocumentType? = null,

    @Json(name = "country")
    val country: kotlin.String? = null,

    /* The result of the KYC check. */
    @Json(name = "result")
    val result: KycPayload.Result? = null,

    /* Array of reason codes for the KYC check. */
    @Json(name = "reasonCodes")
    val reasonCodes: kotlin.collections.List<kotlin.String>? = null,

    /* Optional key-value pairs providing additional context for the request.  Each key should be descriptive, and values should not exceed 2048 characters.  Each key should be descriptive.  */
    @Json(name = "metadata")
    val metadata: kotlin.String? = null

) {

    /**
     * The document type used for verification.
     *
     * Values: PASSPORT,NATIONAL_ID,DRIVER_LICENSE,OTHER
     */
    @JsonClass(generateAdapter = false)
    enum class DocumentType(val value: kotlin.String) {
        @Json(name = "passport") PASSPORT("passport"),
        @Json(name = "national_id") NATIONAL_ID("national_id"),
        @Json(name = "driver_license") DRIVER_LICENSE("driver_license"),
        @Json(name = "other") OTHER("other");
    }
    /**
     * The result of the KYC check.
     *
     * Values: PASSED,FAILED,REVIEW,TIMEOUT,ERROR
     */
    @JsonClass(generateAdapter = false)
    enum class Result(val value: kotlin.String) {
        @Json(name = "passed") PASSED("passed"),
        @Json(name = "failed") FAILED("failed"),
        @Json(name = "review") REVIEW("review"),
        @Json(name = "timeout") TIMEOUT("timeout"),
        @Json(name = "error") ERROR("error");
    }

}
