/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Merchant context for the purchase.
 *
 * @param mcc Merchant Category Code (MCC) for the merchant.
 * @param merchantCountry ISO 3166-1 alpha-2 country code.
 */


data class MerchantContext (

    /* Merchant Category Code (MCC) for the merchant. */
    @Json(name = "mcc")
    val mcc: kotlin.String? = null,

    /* ISO 3166-1 alpha-2 country code. */
    @Json(name = "merchantCountry")
    val merchantCountry: kotlin.String? = null

) {


}
