/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Order context for the purchase.
 *
 * @param orderId Unique identifier for the order.
 * @param orderTotal Value of the purchase in the specified currency. Must be a positive number with up to two decimal places. 
 * @param shippingMethod Shipping method for the order.
 * @param lineItemCount Number of items in the order.
 */


data class OrderContext (

    /* Unique identifier for the order. */
    @Json(name = "orderId")
    val orderId: kotlin.String? = null,

    /* Value of the purchase in the specified currency. Must be a positive number with up to two decimal places.  */
    @Json(name = "orderTotal")
    val orderTotal: kotlin.Float? = null,

    /* Shipping method for the order. */
    @Json(name = "shippingMethod")
    val shippingMethod: OrderContext.ShippingMethod? = null,

    /* Number of items in the order. */
    @Json(name = "lineItemCount")
    val lineItemCount: kotlin.Int? = null

) {

    /**
     * Shipping method for the order.
     *
     * Values: DIGITAL,SHIP,BOPIS
     */
    @JsonClass(generateAdapter = false)
    enum class ShippingMethod(val value: kotlin.String) {
        @Json(name = "digital") DIGITAL("digital"),
        @Json(name = "ship") SHIP("ship"),
        @Json(name = "bopis") BOPIS("bopis");
    }

}
