/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import com.alogram.payrisk.v1.models.AvsResultEnum
import com.alogram.payrisk.v1.models.BankTransfer
import com.alogram.payrisk.v1.models.Card
import com.alogram.payrisk.v1.models.CardNetworkEnum
import com.alogram.payrisk.v1.models.Crypto
import com.alogram.payrisk.v1.models.CvvResultEnum
import com.alogram.payrisk.v1.models.Invoice
import com.alogram.payrisk.v1.models.PaymentCardTypeEnum
import com.alogram.payrisk.v1.models.PaymentRealtimeTypeEnum
import com.alogram.payrisk.v1.models.PaymentWalletTypeEnum
import com.alogram.payrisk.v1.models.Realtime
import com.alogram.payrisk.v1.models.ScaMethodEnum
import com.alogram.payrisk.v1.models.ThreeDSData
import com.alogram.payrisk.v1.models.Wallet

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Union of instrument-specific payment details.
 *
 * @param type Fixed to `card` for this schema.
 * @param cardNetwork 
 * @param cardType 
 * @param bin Bank Identification Number (IIN). First 6–8 digits of the PAN; do not send full PAN.
 * @param issuerCountry ISO 3166-1 alpha-2 country code.
 * @param avsResult 
 * @param cvvResult 
 * @param scaMethod 
 * @param threeDS 
 * @param walletType 
 * @param realtimeType 
 */


interface PaymentMethod {

    /* Fixed to `card` for this schema. */
    @Json(name = "type")
    val type: PaymentMethod.Type
    @Json(name = "cardNetwork")
    val cardNetwork: CardNetworkEnum?
    @Json(name = "cardType")
    val cardType: PaymentCardTypeEnum?
    /* Bank Identification Number (IIN). First 6–8 digits of the PAN; do not send full PAN. */
    @Json(name = "bin")
    val bin: kotlin.String?
    /* ISO 3166-1 alpha-2 country code. */
    @Json(name = "issuerCountry")
    val issuerCountry: kotlin.String?
    @Json(name = "avsResult")
    val avsResult: AvsResultEnum?
    @Json(name = "cvvResult")
    val cvvResult: CvvResultEnum?
    @Json(name = "scaMethod")
    val scaMethod: ScaMethodEnum?
    @Json(name = "threeDS")
    val threeDS: ThreeDSData?
    @Json(name = "walletType")
    val walletType: PaymentWalletTypeEnum?
    @Json(name = "realtimeType")
    val realtimeType: PaymentRealtimeTypeEnum?
    /**
     * Fixed to `card` for this schema.
     *
     * Values: CARD,WALLET,REALTIME,BANK_TRANSFER,CRYPTO,INVOICE
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "card") CARD("card"),
        @Json(name = "wallet") WALLET("wallet"),
        @Json(name = "realtime") REALTIME("realtime"),
        @Json(name = "bank_transfer") BANK_TRANSFER("bank_transfer"),
        @Json(name = "crypto") CRYPTO("crypto"),
        @Json(name = "invoice") INVOICE("invoice");
    }

}
