/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Capture outcome details.
 *
 * @param status Capture status.
 */


data class PaymentCaptureOutcome (

    /* Capture status. */
    @Json(name = "status")
    val status: PaymentCaptureOutcome.Status? = null

) {

    /**
     * Capture status.
     *
     * Values: NONE,PARTIAL,FULL,FAILED
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "none") NONE("none"),
        @Json(name = "partial") PARTIAL("partial"),
        @Json(name = "full") FULL("full"),
        @Json(name = "failed") FAILED("failed");
    }

}
