/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import com.alogram.payrisk.v1.models.PaymentEventType
import com.alogram.payrisk.v1.models.PaymentOutcome

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Payment lifecycle event.
 *
 * @param paymentIntentId Server-minted unique payment identifier.
 * @param eventType 
 * @param timestamp RFC 3339 timestamp with timezone.
 * @param amount Value of the purchase in the specified currency. Must be a positive number with up to two decimal places. 
 * @param currency ISO 4217 currency code (e.g., 'USD').
 * @param outcome 
 * @param metadata Optional key-value pairs providing additional context for the request.  Each key should be descriptive, and values should not exceed 2048 characters.  Each key should be descriptive. 
 */


data class PaymentEvent (

    /* Server-minted unique payment identifier. */
    @Json(name = "paymentIntentId")
    val paymentIntentId: kotlin.String,

    @Json(name = "eventType")
    val eventType: PaymentEventType,

    /* RFC 3339 timestamp with timezone. */
    @Json(name = "timestamp")
    val timestamp: kotlin.String,

    /* Value of the purchase in the specified currency. Must be a positive number with up to two decimal places.  */
    @Json(name = "amount")
    val amount: kotlin.Float? = null,

    /* ISO 4217 currency code (e.g., 'USD'). */
    @Json(name = "currency")
    val currency: kotlin.String? = null,

    @Json(name = "outcome")
    val outcome: PaymentOutcome? = null,

    /* Optional key-value pairs providing additional context for the request.  Each key should be descriptive, and values should not exceed 2048 characters.  Each key should be descriptive.  */
    @Json(name = "metadata")
    val metadata: kotlin.String? = null

) {


}
