/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The type of digital wallet used for the payment.
 *
 * Values: PAYPAL,APPLE_PAY,GOOGLE_PAY,CASH_APP,VENMO
 */

@JsonClass(generateAdapter = false)
enum class PaymentWalletTypeEnum(val value: kotlin.String) {

    @Json(name = "paypal")
    PAYPAL("paypal"),

    @Json(name = "apple_pay")
    APPLE_PAY("apple_pay"),

    @Json(name = "google_pay")
    GOOGLE_PAY("google_pay"),

    @Json(name = "cash_app")
    CASH_APP("cash_app"),

    @Json(name = "venmo")
    VENMO("venmo");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is PaymentWalletTypeEnum) "$data" else null

        /**
         * Returns a valid [PaymentWalletTypeEnum] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): PaymentWalletTypeEnum? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}
