/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The type of payment lifecycle event.
 *
 * Values: AUTHORIZATION,CAPTURE,SETTLEMENT,REFUND,DISPUTE,CHARGEBACK,CHARGEBACK_OUTCOME
 */

@JsonClass(generateAdapter = false)
enum class PaymentEventType(val value: kotlin.String) {

    @Json(name = "authorization")
    AUTHORIZATION("authorization"),

    @Json(name = "capture")
    CAPTURE("capture"),

    @Json(name = "settlement")
    SETTLEMENT("settlement"),

    @Json(name = "refund")
    REFUND("refund"),

    @Json(name = "dispute")
    DISPUTE("dispute"),

    @Json(name = "chargeback")
    CHARGEBACK("chargeback"),

    @Json(name = "chargeback_outcome")
    CHARGEBACK_OUTCOME("chargeback_outcome");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is PaymentEventType) "$data" else null

        /**
         * Returns a valid [PaymentEventType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): PaymentEventType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}
