/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Authorization outcome details.
 *
 * @param approved Indicates whether authorization was approved.
 * @param responseCode Authorization response code.
 */


data class PaymentAuthorizationOutcome (

    /* Indicates whether authorization was approved. */
    @Json(name = "approved")
    val approved: kotlin.Boolean? = null,

    /* Authorization response code. */
    @Json(name = "responseCode")
    val responseCode: kotlin.String? = null

) {


}
