/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Final disposition of the chargeback after investigation/representment.
 *
 * @param status Outcome of the chargeback case.
 */


data class PaymentChargebackOutcome (

    /* Outcome of the chargeback case. */
    @Json(name = "status")
    val status: PaymentChargebackOutcome.Status? = null

) {

    /**
     * Outcome of the chargeback case.
     *
     * Values: WON,LOST,REPRESENTMENT,REVERSED
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "won") WON("won"),
        @Json(name = "lost") LOST("lost"),
        @Json(name = "representment") REPRESENTMENT("representment"),
        @Json(name = "reversed") REVERSED("reversed");
    }

}
