/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Dispute lifecycle status for the transaction.
 *
 * @param status Dispute status.
 */


data class PaymentDisputeOutcome (

    /* Dispute status. */
    @Json(name = "status")
    val status: PaymentDisputeOutcome.Status? = null

) {

    /**
     * Dispute status.
     *
     * Values: NONE,OPEN,WON,LOST,CANCELED
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "none") NONE("none"),
        @Json(name = "open") OPEN("open"),
        @Json(name = "won") WON("won"),
        @Json(name = "lost") LOST("lost"),
        @Json(name = "canceled") CANCELED("canceled");
    }

}
