/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Common base for all payment method variants; determined by `type`.
 *
 * @param type The payment instrument type for this purchase.
 */


data class PaymentMethodBase (

    /* The payment instrument type for this purchase. */
    @Json(name = "type")
    val type: PaymentMethodBase.Type

) {

    /**
     * The payment instrument type for this purchase.
     *
     * Values: CARD,WALLET,REALTIME,BANK_TRANSFER,CRYPTO,INVOICE
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "card") CARD("card"),
        @Json(name = "wallet") WALLET("wallet"),
        @Json(name = "realtime") REALTIME("realtime"),
        @Json(name = "bank_transfer") BANK_TRANSFER("bank_transfer"),
        @Json(name = "crypto") CRYPTO("crypto"),
        @Json(name = "invoice") INVOICE("invoice");
    }

}
