/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The type of real-time payment network used.
 *
 * Values: ZELLE,RTP,FED_NOW,FASTER_PAYMENTS,UPI
 */

@JsonClass(generateAdapter = false)
enum class PaymentRealtimeTypeEnum(val value: kotlin.String) {

    @Json(name = "zelle")
    ZELLE("zelle"),

    @Json(name = "rtp")
    RTP("rtp"),

    @Json(name = "fed_now")
    FED_NOW("fed_now"),

    @Json(name = "faster_payments")
    FASTER_PAYMENTS("faster_payments"),

    @Json(name = "upi")
    UPI("upi");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is PaymentRealtimeTypeEnum) "$data" else null

        /**
         * Returns a valid [PaymentRealtimeTypeEnum] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): PaymentRealtimeTypeEnum? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}
