/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Refund outcome details.
 *
 * @param status Refund status.
 */


data class PaymentRefundOutcome (

    /* Refund status. */
    @Json(name = "status")
    val status: PaymentRefundOutcome.Status? = null

) {

    /**
     * Refund status.
     *
     * Values: NONE,PARTIAL,FULL
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "none") NONE("none"),
        @Json(name = "partial") PARTIAL("partial"),
        @Json(name = "full") FULL("full");
    }

}
