/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import com.alogram.payrisk.v1.models.PaymentAuthorizationOutcome
import com.alogram.payrisk.v1.models.PaymentCaptureOutcome
import com.alogram.payrisk.v1.models.PaymentChargeback
import com.alogram.payrisk.v1.models.PaymentChargebackOutcome
import com.alogram.payrisk.v1.models.PaymentDisputeOutcome
import com.alogram.payrisk.v1.models.PaymentRefundOutcome

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Payment outcome details. Structured by lifecycle stage for clarity and validation. Stages include authorization, capture, refund, dispute, chargeback, and chargebackOutcome. 
 *
 * @param authorization 
 * @param capture 
 * @param refund 
 * @param dispute 
 * @param chargeback 
 * @param chargebackOutcome 
 */


data class PaymentOutcome (

    @Json(name = "authorization")
    val authorization: PaymentAuthorizationOutcome? = null,

    @Json(name = "capture")
    val capture: PaymentCaptureOutcome? = null,

    @Json(name = "refund")
    val refund: PaymentRefundOutcome? = null,

    @Json(name = "dispute")
    val dispute: PaymentDisputeOutcome? = null,

    @Json(name = "chargeback")
    val chargeback: PaymentChargeback? = null,

    @Json(name = "chargebackOutcome")
    val chargebackOutcome: PaymentChargebackOutcome? = null

) : kotlin.collections.HashMap<String, kotlin.Any>() {


}
