/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Chargeback details, including reason code.
 *
 * @param reason Chargeback reason code.
 */


data class PaymentChargeback (

    /* Chargeback reason code. */
    @Json(name = "reason")
    val reason: kotlin.String? = null

) {


}
