/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Postal address used for shipping or billing. Raw values are used only for normalization and risk signals; Alogram will not persist raw address fields in long-term storage. 
 *
 * @param line1 First line of the street address.
 * @param line2 Second line of the street address (apartment, suite, etc.).
 * @param city City or locality.
 * @param region State, province, or region.
 * @param postalCode Postal / ZIP code.
 * @param country ISO 3166-1 alpha-2 country code.
 */


data class PostalAddress (

    /* First line of the street address. */
    @Json(name = "line1")
    val line1: kotlin.String? = null,

    /* Second line of the street address (apartment, suite, etc.). */
    @Json(name = "line2")
    val line2: kotlin.String? = null,

    /* City or locality. */
    @Json(name = "city")
    val city: kotlin.String? = null,

    /* State, province, or region. */
    @Json(name = "region")
    val region: kotlin.String? = null,

    /* Postal / ZIP code. */
    @Json(name = "postalCode")
    val postalCode: kotlin.String? = null,

    /* ISO 3166-1 alpha-2 country code. */
    @Json(name = "country")
    val country: kotlin.String? = null

) {


}
