/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * RFC 7807 Problem Details
 *
 * @param title A short, human-readable summary of the problem type.
 * @param status The HTTP status code applicable to this problem.
 * @param type A URI reference that identifies the problem type.
 * @param detail Human-readable explanation specific to this occurrence.
 * @param instance A URI reference that identifies the specific occurrence.
 * @param errorCode Application-specific error code.
 */


data class Problem (

    /* A short, human-readable summary of the problem type. */
    @Json(name = "title")
    val title: kotlin.String,

    /* The HTTP status code applicable to this problem. */
    @Json(name = "status")
    val status: kotlin.Int,

    /* A URI reference that identifies the problem type. */
    @Json(name = "type")
    val type: java.net.URI? = java.net.URI.create("about:blank"),

    /* Human-readable explanation specific to this occurrence. */
    @Json(name = "detail")
    val detail: kotlin.String? = null,

    /* A URI reference that identifies the specific occurrence. */
    @Json(name = "instance")
    val instance: java.net.URI? = null,

    /* Application-specific error code. */
    @Json(name = "errorCode")
    val errorCode: kotlin.String? = null

) {


}
