/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import com.alogram.payrisk.v1.models.ChannelEnum
import com.alogram.payrisk.v1.models.DeviceInfo
import com.alogram.payrisk.v1.models.EntryMethodEnum
import com.alogram.payrisk.v1.models.MerchantContext
import com.alogram.payrisk.v1.models.OrderContext
import com.alogram.payrisk.v1.models.PayerTypeEnum
import com.alogram.payrisk.v1.models.PaymentMethod
import com.alogram.payrisk.v1.models.StoredCredentialContext

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Purchase details for fraud checks; core fields are common, instrument specifics live in `paymentMethod`. 
 *
 * @param amount Value of the purchase in the specified currency. Must be a positive number with up to two decimal places. 
 * @param currency ISO 4217 currency code (e.g., 'USD').
 * @param paymentMethod 
 * @param locationId Unique identifier for the location where the transaction occurred.
 * @param deviceInfo 
 * @param timestamp RFC 3339 timestamp with timezone.
 * @param transactionId A unique identifier for the transaction. Must be between 3 and 50 characters and only contain alphanumeric characters, underscores, or hyphens. 
 * @param channel 
 * @param entryMethod 
 * @param order 
 * @param payerType 
 * @param storedCredential 
 * @param merchant 
 * @param metadata Optional key-value pairs providing additional context for the request.  Each key should be descriptive, and values should not exceed 2048 characters.  Each key should be descriptive. 
 */


data class Purchase (

    /* Value of the purchase in the specified currency. Must be a positive number with up to two decimal places.  */
    @Json(name = "amount")
    val amount: kotlin.Float,

    /* ISO 4217 currency code (e.g., 'USD'). */
    @Json(name = "currency")
    val currency: kotlin.String,

    @Json(name = "paymentMethod")
    val paymentMethod: PaymentMethod,

    /* Unique identifier for the location where the transaction occurred. */
    @Json(name = "locationId")
    val locationId: kotlin.String? = null,

    @Json(name = "deviceInfo")
    val deviceInfo: DeviceInfo? = null,

    /* RFC 3339 timestamp with timezone. */
    @Json(name = "timestamp")
    val timestamp: kotlin.String? = null,

    /* A unique identifier for the transaction. Must be between 3 and 50 characters and only contain alphanumeric characters, underscores, or hyphens.  */
    @Json(name = "transactionId")
    val transactionId: kotlin.String? = null,

    @Json(name = "channel")
    val channel: ChannelEnum? = null,

    @Json(name = "entryMethod")
    val entryMethod: EntryMethodEnum? = null,

    @Json(name = "order")
    val order: OrderContext? = null,

    @Json(name = "payerType")
    val payerType: PayerTypeEnum? = PayerTypeEnum.CONSUMER,

    @Json(name = "storedCredential")
    val storedCredential: StoredCredentialContext? = null,

    @Json(name = "merchant")
    val merchant: MerchantContext? = null,

    /* Optional key-value pairs providing additional context for the request.  Each key should be descriptive, and values should not exceed 2048 characters.  Each key should be descriptive.  */
    @Json(name = "metadata")
    val metadata: kotlin.String? = null

) {


}
