/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import com.alogram.payrisk.v1.models.PaymentRealtimeTypeEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type Fixed to `realtime` for this schema.
 * @param realtimeType 
 */


data class Realtime (

    /* Fixed to `realtime` for this schema. */
    @Json(name = "type")
    val type: Realtime.Type,

    @Json(name = "realtimeType")
    val realtimeType: PaymentRealtimeTypeEnum? = null

) {

    /**
     * Fixed to `realtime` for this schema.
     *
     * Values: REALTIME
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "realtime") REALTIME("realtime");
    }

}
