/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import com.alogram.payrisk.v1.models.RiskCategoryEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Merchant-friendly detail for a specific risk reason.
 *
 * @param code Technical reason code (e.g., GEO_COUNTRY_SANCTIONED).
 * @param category 
 * @param displayName Merchant-friendly name for the risk reason.
 * @param description Detailed explanation of the risk signal.
 * @param recommendedAction Suggested action for the merchant to mitigate this specific risk.
 */


data class ReasonDetail (

    /* Technical reason code (e.g., GEO_COUNTRY_SANCTIONED). */
    @Json(name = "code")
    val code: kotlin.String,

    @Json(name = "category")
    val category: RiskCategoryEnum,

    /* Merchant-friendly name for the risk reason. */
    @Json(name = "displayName")
    val displayName: kotlin.String,

    /* Detailed explanation of the risk signal. */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* Suggested action for the merchant to mitigate this specific risk. */
    @Json(name = "recommendedAction")
    val recommendedAction: kotlin.String? = null

) {


}
