/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import com.alogram.payrisk.v1.models.CategorySignal

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Breakdown of risk signals by business category.
 *
 * @param geography 
 * @param identity 
 * @param behavior 
 * @param transaction 
 */


data class RiskBreakdown (

    @Json(name = "geography")
    val geography: CategorySignal? = null,

    @Json(name = "identity")
    val identity: CategorySignal? = null,

    @Json(name = "behavior")
    val behavior: CategorySignal? = null,

    @Json(name = "transaction")
    val transaction: CategorySignal? = null

) {


}
