/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The method used for Strong Customer Authentication (SCA).
 *
 * Values: NONE,_3DS_V1,_3DS_V2,OTP_SMS,BIOMETRIC,FIDO2,OTHER
 */

@JsonClass(generateAdapter = false)
enum class ScaMethodEnum(val value: kotlin.String) {

    @Json(name = "none")
    NONE("none"),

    @Json(name = "3ds_v1")
    _3DS_V1("3ds_v1"),

    @Json(name = "3ds_v2")
    _3DS_V2("3ds_v2"),

    @Json(name = "otp_sms")
    OTP_SMS("otp_sms"),

    @Json(name = "biometric")
    BIOMETRIC("biometric"),

    @Json(name = "fido2")
    FIDO2("fido2"),

    @Json(name = "other")
    OTHER("other");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ScaMethodEnum) "$data" else null

        /**
         * Returns a valid [ScaMethodEnum] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ScaMethodEnum? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}
