/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import com.alogram.payrisk.v1.models.EntityIds
import com.alogram.payrisk.v1.models.FraudScore
import com.alogram.payrisk.v1.models.ReasonDetail
import com.alogram.payrisk.v1.models.RiskBreakdown

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Fraud score for a specific transaction or entity.
 *
 * @param assessmentId Universal decision identifier (for purchases, equals paymentIntentId).
 * @param decisionAt RFC 3339 timestamp with timezone.
 * @param decision The synchronous risk decision for a purchase.
 * @param riskScore Fraud risk score (0.00 - 1.00).
 * @param paymentIntentId Server-minted unique payment identifier.
 * @param fraudScore 
 * @param breakdown 
 * @param reasons Structured reason details for the score.
 * @param entities 
 * @param amount Value of the purchase in the specified currency. Must be a positive number with up to two decimal places. 
 * @param currency ISO 4217 currency code (e.g., 'USD').
 */


data class ScoreRecord (

    /* Universal decision identifier (for purchases, equals paymentIntentId). */
    @Json(name = "assessmentId")
    val assessmentId: kotlin.String,

    /* RFC 3339 timestamp with timezone. */
    @Json(name = "decisionAt")
    val decisionAt: kotlin.String,

    /* The synchronous risk decision for a purchase. */
    @Json(name = "decision")
    val decision: ScoreRecord.Decision,

    /* Fraud risk score (0.00 - 1.00). */
    @Json(name = "riskScore")
    val riskScore: kotlin.Float,

    /* Server-minted unique payment identifier. */
    @Json(name = "paymentIntentId")
    val paymentIntentId: kotlin.String? = null,

    @Json(name = "fraudScore")
    val fraudScore: FraudScore? = null,

    @Json(name = "breakdown")
    val breakdown: RiskBreakdown? = null,

    /* Structured reason details for the score. */
    @Json(name = "reasons")
    val reasons: kotlin.collections.List<ReasonDetail>? = null,

    @Json(name = "entities")
    val entities: EntityIds? = null,

    /* Value of the purchase in the specified currency. Must be a positive number with up to two decimal places.  */
    @Json(name = "amount")
    val amount: kotlin.Float? = null,

    /* ISO 4217 currency code (e.g., 'USD'). */
    @Json(name = "currency")
    val currency: kotlin.String? = null

) {

    /**
     * The synchronous risk decision for a purchase.
     *
     * Values: APPROVE,REVIEW,DECLINE,STEP_UP
     */
    @JsonClass(generateAdapter = false)
    enum class Decision(val value: kotlin.String) {
        @Json(name = "approve") APPROVE("approve"),
        @Json(name = "review") REVIEW("review"),
        @Json(name = "decline") DECLINE("decline"),
        @Json(name = "step_up") STEP_UP("step_up");
    }

}
