/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import com.alogram.payrisk.v1.models.ScoreRecord

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * List of fraud scores for a customer.
 *
 * @param scores Score records within the requested window.
 * @param nextPageToken A token for retrieving the next page of results.
 */


data class ScoresSuccessResponse (

    /* Score records within the requested window. */
    @Json(name = "scores")
    val scores: kotlin.collections.List<ScoreRecord>? = null,

    /* A token for retrieving the next page of results. */
    @Json(name = "nextPageToken")
    val nextPageToken: kotlin.String? = null

) {


}
