/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import com.alogram.payrisk.v1.models.Account
import com.alogram.payrisk.v1.models.EntityIds

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Account-level signal variant (single account state snapshot).
 *
 * @param signalType Value for account signals.
 * @param entities 
 * @param account 
 */


data class SignalsAccountVariant (

    /* Value for account signals. */
    @Json(name = "signalType")
    val signalType: SignalsAccountVariant.SignalType,

    @Json(name = "entities")
    val entities: EntityIds,

    @Json(name = "account")
    val account: Account

) {

    /**
     * Value for account signals.
     *
     * Values: ACCOUNT
     */
    @JsonClass(generateAdapter = false)
    enum class SignalType(val value: kotlin.String) {
        @Json(name = "account") ACCOUNT("account");
    }

}
