/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import com.alogram.payrisk.v1.models.EntityIds
import com.alogram.payrisk.v1.models.Interaction

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Interaction batch signal variant (one or more user interactions).
 *
 * @param signalType Value for interaction signals.
 * @param entities 
 * @param interactions One or more interactions associated with the signal.
 */


data class SignalsInteractionVariant (

    /* Value for interaction signals. */
    @Json(name = "signalType")
    val signalType: SignalsInteractionVariant.SignalType,

    @Json(name = "entities")
    val entities: EntityIds,

    /* One or more interactions associated with the signal. */
    @Json(name = "interactions")
    val interactions: kotlin.collections.List<Interaction>

) {

    /**
     * Value for interaction signals.
     *
     * Values: INTERACTION
     */
    @JsonClass(generateAdapter = false)
    enum class SignalType(val value: kotlin.String) {
        @Json(name = "interaction") INTERACTION("interaction");
    }

}
