/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import com.alogram.payrisk.v1.models.Account
import com.alogram.payrisk.v1.models.EntityIds
import com.alogram.payrisk.v1.models.Interaction
import com.alogram.payrisk.v1.models.SignalsAccountVariant
import com.alogram.payrisk.v1.models.SignalsInteractionVariant

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Request for processing application workflow signals. Determined by `signalType`. 
 *
 * @param signalType Value for interaction signals.
 * @param entities 
 * @param account 
 * @param interactions One or more interactions associated with the signal.
 */


interface SignalsRequest {

    /* Value for interaction signals. */
    @Json(name = "signalType")
    val signalType: SignalsRequest.SignalType
    @Json(name = "entities")
    val entities: EntityIds
    @Json(name = "account")
    val account: Account
    /* One or more interactions associated with the signal. */
    @Json(name = "interactions")
    val interactions: kotlin.collections.List<Interaction>
    /**
     * Value for interaction signals.
     *
     * Values: INTERACTION
     */
    @JsonClass(generateAdapter = false)
    enum class SignalType(val value: kotlin.String) {
        @Json(name = "interaction") INTERACTION("interaction");
    }

}
