/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import com.alogram.payrisk.v1.models.PurchaseInitiatorEnum
import com.alogram.payrisk.v1.models.PurchaseSequenceEnum
import com.alogram.payrisk.v1.models.PurchaseUsageEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Minimal stored-credential / recurrence context.
 *
 * @param usage 
 * @param sequence 
 * @param initiator 
 */


data class StoredCredentialContext (

    @Json(name = "usage")
    val usage: PurchaseUsageEnum? = PurchaseUsageEnum.ONE_TIME,

    @Json(name = "sequence")
    val sequence: PurchaseSequenceEnum? = null,

    @Json(name = "initiator")
    val initiator: PurchaseInitiatorEnum? = null

) {


}
