/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 3D Secure (3DS) data for card transactions.
 *
 * @param version The version of the 3D Secure protocol used (e.g., '2.2.0').
 * @param eci Electronic Commerce Indicator. Values indicate the outcome of 3D Secure authentication. 
 * @param flow The flow of the 3D Secure authentication. 'frictionless' means no challenge was presented to the cardholder, 'challenge' means the cardholder was challenged. 
 * @param liabilityShift Indicates whether liability for chargebacks has shifted to the issuer (true) or remains with the merchant (false). 
 * @param cavvPresent Indicates whether the Cardholder Authentication Verification Value (CAVV) was present in the 3DS message. 
 */


data class ThreeDSData (

    /* The version of the 3D Secure protocol used (e.g., '2.2.0'). */
    @Json(name = "version")
    val version: kotlin.String? = null,

    /* Electronic Commerce Indicator. Values indicate the outcome of 3D Secure authentication.  */
    @Json(name = "eci")
    val eci: kotlin.String? = null,

    /* The flow of the 3D Secure authentication. 'frictionless' means no challenge was presented to the cardholder, 'challenge' means the cardholder was challenged.  */
    @Json(name = "flow")
    val flow: ThreeDSData.Flow? = null,

    /* Indicates whether liability for chargebacks has shifted to the issuer (true) or remains with the merchant (false).  */
    @Json(name = "liabilityShift")
    val liabilityShift: kotlin.Boolean? = null,

    /* Indicates whether the Cardholder Authentication Verification Value (CAVV) was present in the 3DS message.  */
    @Json(name = "cavvPresent")
    val cavvPresent: kotlin.Boolean? = null

) {

    /**
     * The flow of the 3D Secure authentication. 'frictionless' means no challenge was presented to the cardholder, 'challenge' means the cardholder was challenged. 
     *
     * Values: FRICTIONLESS,CHALLENGE
     */
    @JsonClass(generateAdapter = false)
    enum class Flow(val value: kotlin.String) {
        @Json(name = "frictionless") FRICTIONLESS("frictionless"),
        @Json(name = "challenge") CHALLENGE("challenge");
    }

}
