/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import com.alogram.payrisk.v1.models.PaymentWalletTypeEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type Fixed to `wallet` for this schema.
 * @param walletType 
 */


data class Wallet (

    /* Fixed to `wallet` for this schema. */
    @Json(name = "type")
    val type: Wallet.Type,

    @Json(name = "walletType")
    val walletType: PaymentWalletTypeEnum? = null

) {

    /**
     * Fixed to `wallet` for this schema.
     *
     * Values: WALLET
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "wallet") WALLET("wallet");
    }

}
