/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.alogram.payrisk.v1.models.CategorySignal
import com.alogram.payrisk.v1.models.RiskLevelEnum

class CategorySignalTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CategorySignal
        //val modelInstance = CategorySignal()

        // to test the property `level`
        should("test level") {
            // uncomment below to test the property
            //modelInstance.level shouldBe ("TODO")
        }

        // to test the property `score` - Category-specific risk score (0.00 - 1.00).
        should("test score") {
            // uncomment below to test the property
            //modelInstance.score shouldBe ("TODO")
        }

        // to test the property `reasons` - Specific reason codes for this category.
        should("test reasons") {
            // uncomment below to test the property
            //modelInstance.reasons shouldBe ("TODO")
        }

    }
}
