/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.alogram.payrisk.v1.models.CheckRequest
import com.alogram.payrisk.v1.models.EntityIds
import com.alogram.payrisk.v1.models.Identity
import com.alogram.payrisk.v1.models.Purchase

class CheckRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CheckRequest
        //val modelInstance = CheckRequest()

        // to test the property `entities`
        should("test entities") {
            // uncomment below to test the property
            //modelInstance.entities shouldBe ("TODO")
        }

        // to test the property `purchase`
        should("test purchase") {
            // uncomment below to test the property
            //modelInstance.purchase shouldBe ("TODO")
        }

        // to test the property `eventType` - (optional) event being checked, this may expand later beyond 'purchase'.
        should("test eventType") {
            // uncomment below to test the property
            //modelInstance.eventType shouldBe ("TODO")
        }

        // to test the property `paymentIntentId` - Server-minted unique payment identifier.
        should("test paymentIntentId") {
            // uncomment below to test the property
            //modelInstance.paymentIntentId shouldBe ("TODO")
        }

        // to test the property `identity`
        should("test identity") {
            // uncomment below to test the property
            //modelInstance.identity shouldBe ("TODO")
        }

    }
}
