/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.alogram.payrisk.v1.models.DecisionResponse
import com.alogram.payrisk.v1.models.FraudScore
import com.alogram.payrisk.v1.models.ReasonDetail
import com.alogram.payrisk.v1.models.RiskBreakdown

class DecisionResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DecisionResponse
        //val modelInstance = DecisionResponse()

        // to test the property `assessmentId` - Universal decision identifier. For purchases, equals paymentIntentId.
        should("test assessmentId") {
            // uncomment below to test the property
            //modelInstance.assessmentId shouldBe ("TODO")
        }

        // to test the property `decision`
        should("test decision") {
            // uncomment below to test the property
            //modelInstance.decision shouldBe ("TODO")
        }

        // to test the property `decisionAt` - RFC 3339 timestamp with timezone.
        should("test decisionAt") {
            // uncomment below to test the property
            //modelInstance.decisionAt shouldBe ("TODO")
        }

        // to test the property `riskScore`
        should("test riskScore") {
            // uncomment below to test the property
            //modelInstance.riskScore shouldBe ("TODO")
        }

        // to test the property `fraudScore`
        should("test fraudScore") {
            // uncomment below to test the property
            //modelInstance.fraudScore shouldBe ("TODO")
        }

        // to test the property `breakdown`
        should("test breakdown") {
            // uncomment below to test the property
            //modelInstance.breakdown shouldBe ("TODO")
        }

        // to test the property `reasonCodes` - Technical reason codes for the decision.
        should("test reasonCodes") {
            // uncomment below to test the property
            //modelInstance.reasonCodes shouldBe ("TODO")
        }

        // to test the property `reasons` - Structured reason details for the decision.
        should("test reasons") {
            // uncomment below to test the property
            //modelInstance.reasons shouldBe ("TODO")
        }

        // to test the property `actions`
        should("test actions") {
            // uncomment below to test the property
            //modelInstance.actions shouldBe ("TODO")
        }

        // to test the property `paymentIntentId` - Server-minted unique payment identifier.
        should("test paymentIntentId") {
            // uncomment below to test the property
            //modelInstance.paymentIntentId shouldBe ("TODO")
        }

        // to test the property `policyVersion` - The version of the policy that generated the decision.
        should("test policyVersion") {
            // uncomment below to test the property
            //modelInstance.policyVersion shouldBe ("TODO")
        }

        // to test the property `modelVersion` - The version of the model that generated the decision.
        should("test modelVersion") {
            // uncomment below to test the property
            //modelInstance.modelVersion shouldBe ("TODO")
        }

        // to test the property `ttlSeconds` - Time to live for the decision in seconds.
        should("test ttlSeconds") {
            // uncomment below to test the property
            //modelInstance.ttlSeconds shouldBe ("TODO")
        }

    }
}
