/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.alogram.payrisk.v1.models.DeviceInfo
import com.alogram.payrisk.v1.models.Integrity
import com.alogram.payrisk.v1.models.IpInfo

class DeviceInfoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DeviceInfo
        //val modelInstance = DeviceInfo()

        // to test the property `fingerprint` - Unique hash representing the device's fingerprint. Lowercase hex. Prefix \"fp_\". 
        should("test fingerprint") {
            // uncomment below to test the property
            //modelInstance.fingerprint shouldBe ("TODO")
        }

        // to test the property `userAgent` - Browser's User-Agent string, useful for identifying OS and browser type.  Must be between 10 and 512 printable ASCII characters. 
        should("test userAgent") {
            // uncomment below to test the property
            //modelInstance.userAgent shouldBe ("TODO")
        }

        // to test the property `ip`
        should("test ip") {
            // uncomment below to test the property
            //modelInstance.ip shouldBe ("TODO")
        }

        // to test the property `integrity`
        should("test integrity") {
            // uncomment below to test the property
            //modelInstance.integrity shouldBe ("TODO")
        }

    }
}
