/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.alogram.payrisk.v1.models.EntityIds

class EntityIdsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EntityIds
        //val modelInstance = EntityIds()

        // to test the property `tenantId` - Canonical ID for the paying organization (Tenant). Opaque, immutable, lowercase.  Must start with \"tid_\". Do not use domains or emails here. For a tenant's domain,  use a separate field (e.g., tenantDomain). 
        should("test tenantId") {
            // uncomment below to test the property
            //modelInstance.tenantId shouldBe ("TODO")
        }

        // to test the property `clientId` - Canonical ID for the Tenant’s business customer (e.g., merchant/partner).  Opaque, immutable, lowercase. Must start with 'cid_'. 
        should("test clientId") {
            // uncomment below to test the property
            //modelInstance.clientId shouldBe ("TODO")
        }

        // to test the property `endCustomerId` - Canonical ID for the client’s end user / consumer (account holder).  Opaque, immutable, lowercase. Must start with \"ecid_\".  Do not put PII (like emails or phone numbers) in this field. 
        should("test endCustomerId") {
            // uncomment below to test the property
            //modelInstance.endCustomerId shouldBe ("TODO")
        }

        // to test the property `memberId` - Canonical ID for a Tenant member/operator (employee/contractor) using the platform.  Opaque, immutable, lowercase. Must start with 'mid_'. 
        should("test memberId") {
            // uncomment below to test the property
            //modelInstance.memberId shouldBe ("TODO")
        }

        // to test the property `paymentInstrumentId` - Tokenized instrument ID (non-PCI).
        should("test paymentInstrumentId") {
            // uncomment below to test the property
            //modelInstance.paymentInstrumentId shouldBe ("TODO")
        }

        // to test the property `deviceId` - Server-issued stable device token (device-level identifier). Should persist across sessions and logins on the same browser/device. 
        should("test deviceId") {
            // uncomment below to test the property
            //modelInstance.deviceId shouldBe ("TODO")
        }

        // to test the property `sessionId` - Application/user session identifier (login or checkout session). Typically rotates more frequently than deviceId and may be tied to authentication. 
        should("test sessionId") {
            // uncomment below to test the property
            //modelInstance.sessionId shouldBe ("TODO")
        }

        // to test the property `emailHash` - Normalized+lowercased email hash (e.g., sha256).
        should("test emailHash") {
            // uncomment below to test the property
            //modelInstance.emailHash shouldBe ("TODO")
        }

        // to test the property `emailDomainHash` - Normalized+lowercased email *domain* hash (e.g., sha256).
        should("test emailDomainHash") {
            // uncomment below to test the property
            //modelInstance.emailDomainHash shouldBe ("TODO")
        }

        // to test the property `phoneHash` - Normalized+lowercased phone hash (e.g., sha256).
        should("test phoneHash") {
            // uncomment below to test the property
            //modelInstance.phoneHash shouldBe ("TODO")
        }

        // to test the property `shippingAddressHash` - Normalized+lowercased shipping address hash (e.g., sha256).
        should("test shippingAddressHash") {
            // uncomment below to test the property
            //modelInstance.shippingAddressHash shouldBe ("TODO")
        }

        // to test the property `billingAddressHash` - Normalized+lowercased billing address hash (e.g., sha256).
        should("test billingAddressHash") {
            // uncomment below to test the property
            //modelInstance.billingAddressHash shouldBe ("TODO")
        }

    }
}
