/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.alogram.payrisk.v1.models.FraudScore
import com.alogram.payrisk.v1.models.ConfidenceEnum
import com.alogram.payrisk.v1.models.RiskLevelEnum

class FraudScoreTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of FraudScore
        //val modelInstance = FraudScore()

        // to test the property `riskLevel`
        should("test riskLevel") {
            // uncomment below to test the property
            //modelInstance.riskLevel shouldBe ("TODO")
        }

        // to test the property `confidence`
        should("test confidence") {
            // uncomment below to test the property
            //modelInstance.confidence shouldBe ("TODO")
        }

        // to test the property `score` - Fraud risk score (0.00 - 1.00).
        should("test score") {
            // uncomment below to test the property
            //modelInstance.score shouldBe ("TODO")
        }

        // to test the property `explanation` - A human-readable explanation of the fraud score, if available.
        should("test explanation") {
            // uncomment below to test the property
            //modelInstance.explanation shouldBe ("TODO")
        }

    }
}
