/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.alogram.payrisk.v1.models.Identity
import com.alogram.payrisk.v1.models.PostalAddress

class IdentityTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Identity
        //val modelInstance = Identity()

        // to test the property `email` - Email address of the customer.
        should("test email") {
            // uncomment below to test the property
            //modelInstance.email shouldBe ("TODO")
        }

        // to test the property `emailDomain` - Email domain only (no local part). Useful for domain-level risk and allow/deny lists without sending full email PII. Example: \"gmail.com\", \"merchant-example.co.uk\" 
        should("test emailDomain") {
            // uncomment below to test the property
            //modelInstance.emailDomain shouldBe ("TODO")
        }

        // to test the property `phone` - Phone number that supports international E.164 format, as well as spaces, dashes, and parentheses.  Examples: \"+1 (415) 555-2671\", \"415-555-2671\", \"+14155552671\" 
        should("test phone") {
            // uncomment below to test the property
            //modelInstance.phone shouldBe ("TODO")
        }

        // to test the property `shippingAddress`
        should("test shippingAddress") {
            // uncomment below to test the property
            //modelInstance.shippingAddress shouldBe ("TODO")
        }

        // to test the property `billingAddress`
        should("test billingAddress") {
            // uncomment below to test the property
            //modelInstance.billingAddress shouldBe ("TODO")
        }

    }
}
