/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.alogram.payrisk.v1.models.Integrity

class IntegrityTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Integrity
        //val modelInstance = Integrity()

        // to test the property `isProxyVpnTor` - Indicates whether the IP address is associated with a proxy, VPN, or Tor exit node. 
        should("test isProxyVpnTor") {
            // uncomment below to test the property
            //modelInstance.isProxyVpnTor shouldBe ("TODO")
        }

        // to test the property `isHostingProvider` - Indicates whether the IP address belongs to a hosting provider (e.g., data center, cloud provider). 
        should("test isHostingProvider") {
            // uncomment below to test the property
            //modelInstance.isHostingProvider shouldBe ("TODO")
        }

        // to test the property `isHeadless` - Indicates whether the browser is running in headless mode (e.g., automated testing, scraping). 
        should("test isHeadless") {
            // uncomment below to test the property
            //modelInstance.isHeadless shouldBe ("TODO")
        }

        // to test the property `isAutomation` - Indicates whether the request originated from an automated script or bot. 
        should("test isAutomation") {
            // uncomment below to test the property
            //modelInstance.isAutomation shouldBe ("TODO")
        }

        // to test the property `isEmulator` - Indicates whether the request originated from an emulator (e.g., Android Emulator, iOS Simulator). 
        should("test isEmulator") {
            // uncomment below to test the property
            //modelInstance.isEmulator shouldBe ("TODO")
        }

        // to test the property `isRootedJailbroken` - Indicates whether the device is rooted (Android) or jailbroken (iOS). 
        should("test isRootedJailbroken") {
            // uncomment below to test the property
            //modelInstance.isRootedJailbroken shouldBe ("TODO")
        }

    }
}
