/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.alogram.payrisk.v1.models.Interaction
import com.alogram.payrisk.v1.models.DeviceInfo
import com.alogram.payrisk.v1.models.InteractionTypeEnum

class InteractionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Interaction
        //val modelInstance = Interaction()

        // to test the property `interactionType`
        should("test interactionType") {
            // uncomment below to test the property
            //modelInstance.interactionType shouldBe ("TODO")
        }

        // to test the property `locationId` - Unique identifier for the location where the transaction occurred.
        should("test locationId") {
            // uncomment below to test the property
            //modelInstance.locationId shouldBe ("TODO")
        }

        // to test the property `deviceInfo`
        should("test deviceInfo") {
            // uncomment below to test the property
            //modelInstance.deviceInfo shouldBe ("TODO")
        }

        // to test the property `timestamp` - RFC 3339 timestamp with timezone.
        should("test timestamp") {
            // uncomment below to test the property
            //modelInstance.timestamp shouldBe ("TODO")
        }

        // to test the property `metadata` - Optional key-value pairs providing additional context for the request.  Each key should be descriptive, and values should not exceed 2048 characters.  Each key should be descriptive. 
        should("test metadata") {
            // uncomment below to test the property
            //modelInstance.metadata shouldBe ("TODO")
        }

    }
}
