/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.alogram.payrisk.v1.models.IpInfo

class IpInfoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of IpInfo
        //val modelInstance = IpInfo()

        // to test the property `ipAddress` - IP address of the customer, client, or user that initiated the request. Each octet must be between 0 and 255. 
        should("test ipAddress") {
            // uncomment below to test the property
            //modelInstance.ipAddress shouldBe ("TODO")
        }

        // to test the property `ipv6` - IPv6 address.
        should("test ipv6") {
            // uncomment below to test the property
            //modelInstance.ipv6 shouldBe ("TODO")
        }

        // to test the property `ipVersion` - IP protocol version.
        should("test ipVersion") {
            // uncomment below to test the property
            //modelInstance.ipVersion shouldBe ("TODO")
        }

        // to test the property `ipPrefix` - CIDR, e.g., 198.51.100.0/24 or 2001:db8::/48
        should("test ipPrefix") {
            // uncomment below to test the property
            //modelInstance.ipPrefix shouldBe ("TODO")
        }

        // to test the property `asn` - Autonomous System Number (ASN) of the IP address.
        should("test asn") {
            // uncomment below to test the property
            //modelInstance.asn shouldBe ("TODO")
        }

        // to test the property `org` - Organization associated with the IP address.
        should("test org") {
            // uncomment below to test the property
            //modelInstance.org shouldBe ("TODO")
        }

        // to test the property `company` - Company associated with the IP address.
        should("test company") {
            // uncomment below to test the property
            //modelInstance.company shouldBe ("TODO")
        }

        // to test the property `country` - ISO 3166-1 alpha-2 country code.
        should("test country") {
            // uncomment below to test the property
            //modelInstance.country shouldBe ("TODO")
        }

        // to test the property `region` - Region associated with the IP address.
        should("test region") {
            // uncomment below to test the property
            //modelInstance.region shouldBe ("TODO")
        }

        // to test the property `city` - City associated with the IP address.
        should("test city") {
            // uncomment below to test the property
            //modelInstance.city shouldBe ("TODO")
        }

        // to test the property `postalCode` - Postal code associated with the IP address.
        should("test postalCode") {
            // uncomment below to test the property
            //modelInstance.postalCode shouldBe ("TODO")
        }

    }
}
