/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.alogram.payrisk.v1.models.KycCheckRequest
import com.alogram.payrisk.v1.models.Account
import com.alogram.payrisk.v1.models.EntityIds
import com.alogram.payrisk.v1.models.KycPayload

class KycCheckRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of KycCheckRequest
        //val modelInstance = KycCheckRequest()

        // to test the property `eventSubtype` - The specific subtype of the KYC event.
        should("test eventSubtype") {
            // uncomment below to test the property
            //modelInstance.eventSubtype shouldBe ("TODO")
        }

        // to test the property `account`
        should("test account") {
            // uncomment below to test the property
            //modelInstance.account shouldBe ("TODO")
        }

        // to test the property `entities`
        should("test entities") {
            // uncomment below to test the property
            //modelInstance.entities shouldBe ("TODO")
        }

        // to test the property `kyc`
        should("test kyc") {
            // uncomment below to test the property
            //modelInstance.kyc shouldBe ("TODO")
        }

    }
}
