/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.alogram.payrisk.v1.models.MerchantContext

class MerchantContextTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MerchantContext
        //val modelInstance = MerchantContext()

        // to test the property `mcc` - Merchant Category Code (MCC) for the merchant.
        should("test mcc") {
            // uncomment below to test the property
            //modelInstance.mcc shouldBe ("TODO")
        }

        // to test the property `merchantCountry` - ISO 3166-1 alpha-2 country code.
        should("test merchantCountry") {
            // uncomment below to test the property
            //modelInstance.merchantCountry shouldBe ("TODO")
        }

    }
}
