/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.alogram.payrisk.v1.models.OrderContext

class OrderContextTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OrderContext
        //val modelInstance = OrderContext()

        // to test the property `orderId` - Unique identifier for the order.
        should("test orderId") {
            // uncomment below to test the property
            //modelInstance.orderId shouldBe ("TODO")
        }

        // to test the property `orderTotal` - Value of the purchase in the specified currency. Must be a positive number with up to two decimal places. 
        should("test orderTotal") {
            // uncomment below to test the property
            //modelInstance.orderTotal shouldBe ("TODO")
        }

        // to test the property `shippingMethod` - Shipping method for the order.
        should("test shippingMethod") {
            // uncomment below to test the property
            //modelInstance.shippingMethod shouldBe ("TODO")
        }

        // to test the property `lineItemCount` - Number of items in the order.
        should("test lineItemCount") {
            // uncomment below to test the property
            //modelInstance.lineItemCount shouldBe ("TODO")
        }

    }
}
