/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.alogram.payrisk.v1.models.PaymentEvent
import com.alogram.payrisk.v1.models.PaymentEventType
import com.alogram.payrisk.v1.models.PaymentOutcome

class PaymentEventTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PaymentEvent
        //val modelInstance = PaymentEvent()

        // to test the property `paymentIntentId` - Server-minted unique payment identifier.
        should("test paymentIntentId") {
            // uncomment below to test the property
            //modelInstance.paymentIntentId shouldBe ("TODO")
        }

        // to test the property `eventType`
        should("test eventType") {
            // uncomment below to test the property
            //modelInstance.eventType shouldBe ("TODO")
        }

        // to test the property `timestamp` - RFC 3339 timestamp with timezone.
        should("test timestamp") {
            // uncomment below to test the property
            //modelInstance.timestamp shouldBe ("TODO")
        }

        // to test the property `amount` - Value of the purchase in the specified currency. Must be a positive number with up to two decimal places. 
        should("test amount") {
            // uncomment below to test the property
            //modelInstance.amount shouldBe ("TODO")
        }

        // to test the property `currency` - ISO 4217 currency code (e.g., 'USD').
        should("test currency") {
            // uncomment below to test the property
            //modelInstance.currency shouldBe ("TODO")
        }

        // to test the property `outcome`
        should("test outcome") {
            // uncomment below to test the property
            //modelInstance.outcome shouldBe ("TODO")
        }

        // to test the property `metadata` - Optional key-value pairs providing additional context for the request.  Each key should be descriptive, and values should not exceed 2048 characters.  Each key should be descriptive. 
        should("test metadata") {
            // uncomment below to test the property
            //modelInstance.metadata shouldBe ("TODO")
        }

    }
}
