/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.alogram.payrisk.v1.models.PaymentAuthorizationOutcome

class PaymentAuthorizationOutcomeTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PaymentAuthorizationOutcome
        //val modelInstance = PaymentAuthorizationOutcome()

        // to test the property `approved` - Indicates whether authorization was approved.
        should("test approved") {
            // uncomment below to test the property
            //modelInstance.approved shouldBe ("TODO")
        }

        // to test the property `responseCode` - Authorization response code.
        should("test responseCode") {
            // uncomment below to test the property
            //modelInstance.responseCode shouldBe ("TODO")
        }

    }
}
