/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.alogram.payrisk.v1.models.PaymentChargeback

class PaymentChargebackTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PaymentChargeback
        //val modelInstance = PaymentChargeback()

        // to test the property `reason` - Chargeback reason code.
        should("test reason") {
            // uncomment below to test the property
            //modelInstance.reason shouldBe ("TODO")
        }

    }
}
