/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.alogram.payrisk.v1.models.PaymentOutcome
import com.alogram.payrisk.v1.models.PaymentAuthorizationOutcome
import com.alogram.payrisk.v1.models.PaymentCaptureOutcome
import com.alogram.payrisk.v1.models.PaymentChargeback
import com.alogram.payrisk.v1.models.PaymentChargebackOutcome
import com.alogram.payrisk.v1.models.PaymentDisputeOutcome
import com.alogram.payrisk.v1.models.PaymentRefundOutcome

class PaymentOutcomeTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PaymentOutcome
        //val modelInstance = PaymentOutcome()

        // to test the property `authorization`
        should("test authorization") {
            // uncomment below to test the property
            //modelInstance.authorization shouldBe ("TODO")
        }

        // to test the property `capture`
        should("test capture") {
            // uncomment below to test the property
            //modelInstance.capture shouldBe ("TODO")
        }

        // to test the property `refund`
        should("test refund") {
            // uncomment below to test the property
            //modelInstance.refund shouldBe ("TODO")
        }

        // to test the property `dispute`
        should("test dispute") {
            // uncomment below to test the property
            //modelInstance.dispute shouldBe ("TODO")
        }

        // to test the property `chargeback`
        should("test chargeback") {
            // uncomment below to test the property
            //modelInstance.chargeback shouldBe ("TODO")
        }

        // to test the property `chargebackOutcome`
        should("test chargebackOutcome") {
            // uncomment below to test the property
            //modelInstance.chargebackOutcome shouldBe ("TODO")
        }

    }
}
