/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.alogram.payrisk.v1.models.PaymentMethod
import com.alogram.payrisk.v1.models.AvsResultEnum
import com.alogram.payrisk.v1.models.BankTransfer
import com.alogram.payrisk.v1.models.Card
import com.alogram.payrisk.v1.models.CardNetworkEnum
import com.alogram.payrisk.v1.models.Crypto
import com.alogram.payrisk.v1.models.CvvResultEnum
import com.alogram.payrisk.v1.models.Invoice
import com.alogram.payrisk.v1.models.PaymentCardTypeEnum
import com.alogram.payrisk.v1.models.PaymentRealtimeTypeEnum
import com.alogram.payrisk.v1.models.PaymentWalletTypeEnum
import com.alogram.payrisk.v1.models.Realtime
import com.alogram.payrisk.v1.models.ScaMethodEnum
import com.alogram.payrisk.v1.models.ThreeDSData
import com.alogram.payrisk.v1.models.Wallet

class PaymentMethodTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PaymentMethod
        //val modelInstance = PaymentMethod()

        // to test the property `type` - Fixed to `card` for this schema.
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `cardNetwork`
        should("test cardNetwork") {
            // uncomment below to test the property
            //modelInstance.cardNetwork shouldBe ("TODO")
        }

        // to test the property `cardType`
        should("test cardType") {
            // uncomment below to test the property
            //modelInstance.cardType shouldBe ("TODO")
        }

        // to test the property `bin` - Bank Identification Number (IIN). First 6–8 digits of the PAN; do not send full PAN.
        should("test bin") {
            // uncomment below to test the property
            //modelInstance.bin shouldBe ("TODO")
        }

        // to test the property `issuerCountry` - ISO 3166-1 alpha-2 country code.
        should("test issuerCountry") {
            // uncomment below to test the property
            //modelInstance.issuerCountry shouldBe ("TODO")
        }

        // to test the property `avsResult`
        should("test avsResult") {
            // uncomment below to test the property
            //modelInstance.avsResult shouldBe ("TODO")
        }

        // to test the property `cvvResult`
        should("test cvvResult") {
            // uncomment below to test the property
            //modelInstance.cvvResult shouldBe ("TODO")
        }

        // to test the property `scaMethod`
        should("test scaMethod") {
            // uncomment below to test the property
            //modelInstance.scaMethod shouldBe ("TODO")
        }

        // to test the property `threeDS`
        should("test threeDS") {
            // uncomment below to test the property
            //modelInstance.threeDS shouldBe ("TODO")
        }

        // to test the property `walletType`
        should("test walletType") {
            // uncomment below to test the property
            //modelInstance.walletType shouldBe ("TODO")
        }

        // to test the property `realtimeType`
        should("test realtimeType") {
            // uncomment below to test the property
            //modelInstance.realtimeType shouldBe ("TODO")
        }

    }
}
