/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.alogram.payrisk.v1.models.PostalAddress

class PostalAddressTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PostalAddress
        //val modelInstance = PostalAddress()

        // to test the property `line1` - First line of the street address.
        should("test line1") {
            // uncomment below to test the property
            //modelInstance.line1 shouldBe ("TODO")
        }

        // to test the property `line2` - Second line of the street address (apartment, suite, etc.).
        should("test line2") {
            // uncomment below to test the property
            //modelInstance.line2 shouldBe ("TODO")
        }

        // to test the property `city` - City or locality.
        should("test city") {
            // uncomment below to test the property
            //modelInstance.city shouldBe ("TODO")
        }

        // to test the property `region` - State, province, or region.
        should("test region") {
            // uncomment below to test the property
            //modelInstance.region shouldBe ("TODO")
        }

        // to test the property `postalCode` - Postal / ZIP code.
        should("test postalCode") {
            // uncomment below to test the property
            //modelInstance.postalCode shouldBe ("TODO")
        }

        // to test the property `country` - ISO 3166-1 alpha-2 country code.
        should("test country") {
            // uncomment below to test the property
            //modelInstance.country shouldBe ("TODO")
        }

    }
}
