/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.alogram.payrisk.v1.models.Problem

class ProblemTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Problem
        //val modelInstance = Problem()

        // to test the property `title` - A short, human-readable summary of the problem type.
        should("test title") {
            // uncomment below to test the property
            //modelInstance.title shouldBe ("TODO")
        }

        // to test the property `status` - The HTTP status code applicable to this problem.
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `type` - A URI reference that identifies the problem type.
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `detail` - Human-readable explanation specific to this occurrence.
        should("test detail") {
            // uncomment below to test the property
            //modelInstance.detail shouldBe ("TODO")
        }

        // to test the property `instance` - A URI reference that identifies the specific occurrence.
        should("test instance") {
            // uncomment below to test the property
            //modelInstance.instance shouldBe ("TODO")
        }

        // to test the property `errorCode` - Application-specific error code.
        should("test errorCode") {
            // uncomment below to test the property
            //modelInstance.errorCode shouldBe ("TODO")
        }

    }
}
