/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.alogram.payrisk.v1.models.Purchase
import com.alogram.payrisk.v1.models.ChannelEnum
import com.alogram.payrisk.v1.models.DeviceInfo
import com.alogram.payrisk.v1.models.EntryMethodEnum
import com.alogram.payrisk.v1.models.MerchantContext
import com.alogram.payrisk.v1.models.OrderContext
import com.alogram.payrisk.v1.models.PayerTypeEnum
import com.alogram.payrisk.v1.models.PaymentMethod
import com.alogram.payrisk.v1.models.StoredCredentialContext

class PurchaseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Purchase
        //val modelInstance = Purchase()

        // to test the property `amount` - Value of the purchase in the specified currency. Must be a positive number with up to two decimal places. 
        should("test amount") {
            // uncomment below to test the property
            //modelInstance.amount shouldBe ("TODO")
        }

        // to test the property `currency` - ISO 4217 currency code (e.g., 'USD').
        should("test currency") {
            // uncomment below to test the property
            //modelInstance.currency shouldBe ("TODO")
        }

        // to test the property `paymentMethod`
        should("test paymentMethod") {
            // uncomment below to test the property
            //modelInstance.paymentMethod shouldBe ("TODO")
        }

        // to test the property `locationId` - Unique identifier for the location where the transaction occurred.
        should("test locationId") {
            // uncomment below to test the property
            //modelInstance.locationId shouldBe ("TODO")
        }

        // to test the property `deviceInfo`
        should("test deviceInfo") {
            // uncomment below to test the property
            //modelInstance.deviceInfo shouldBe ("TODO")
        }

        // to test the property `timestamp` - RFC 3339 timestamp with timezone.
        should("test timestamp") {
            // uncomment below to test the property
            //modelInstance.timestamp shouldBe ("TODO")
        }

        // to test the property `transactionId` - A unique identifier for the transaction. Must be between 3 and 50 characters and only contain alphanumeric characters, underscores, or hyphens. 
        should("test transactionId") {
            // uncomment below to test the property
            //modelInstance.transactionId shouldBe ("TODO")
        }

        // to test the property `channel`
        should("test channel") {
            // uncomment below to test the property
            //modelInstance.channel shouldBe ("TODO")
        }

        // to test the property `entryMethod`
        should("test entryMethod") {
            // uncomment below to test the property
            //modelInstance.entryMethod shouldBe ("TODO")
        }

        // to test the property `order`
        should("test order") {
            // uncomment below to test the property
            //modelInstance.order shouldBe ("TODO")
        }

        // to test the property `payerType`
        should("test payerType") {
            // uncomment below to test the property
            //modelInstance.payerType shouldBe ("TODO")
        }

        // to test the property `storedCredential`
        should("test storedCredential") {
            // uncomment below to test the property
            //modelInstance.storedCredential shouldBe ("TODO")
        }

        // to test the property `merchant`
        should("test merchant") {
            // uncomment below to test the property
            //modelInstance.merchant shouldBe ("TODO")
        }

        // to test the property `metadata` - Optional key-value pairs providing additional context for the request.  Each key should be descriptive, and values should not exceed 2048 characters.  Each key should be descriptive. 
        should("test metadata") {
            // uncomment below to test the property
            //modelInstance.metadata shouldBe ("TODO")
        }

    }
}
