/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.alogram.payrisk.v1.models.ReasonDetail
import com.alogram.payrisk.v1.models.RiskCategoryEnum

class ReasonDetailTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ReasonDetail
        //val modelInstance = ReasonDetail()

        // to test the property `code` - Technical reason code (e.g., GEO_COUNTRY_SANCTIONED).
        should("test code") {
            // uncomment below to test the property
            //modelInstance.code shouldBe ("TODO")
        }

        // to test the property `category`
        should("test category") {
            // uncomment below to test the property
            //modelInstance.category shouldBe ("TODO")
        }

        // to test the property `displayName` - Merchant-friendly name for the risk reason.
        should("test displayName") {
            // uncomment below to test the property
            //modelInstance.displayName shouldBe ("TODO")
        }

        // to test the property `description` - Detailed explanation of the risk signal.
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `recommendedAction` - Suggested action for the merchant to mitigate this specific risk.
        should("test recommendedAction") {
            // uncomment below to test the property
            //modelInstance.recommendedAction shouldBe ("TODO")
        }

    }
}
