/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.alogram.payrisk.v1.models.RiskBreakdown
import com.alogram.payrisk.v1.models.CategorySignal

class RiskBreakdownTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RiskBreakdown
        //val modelInstance = RiskBreakdown()

        // to test the property `geography`
        should("test geography") {
            // uncomment below to test the property
            //modelInstance.geography shouldBe ("TODO")
        }

        // to test the property `identity`
        should("test identity") {
            // uncomment below to test the property
            //modelInstance.identity shouldBe ("TODO")
        }

        // to test the property `behavior`
        should("test behavior") {
            // uncomment below to test the property
            //modelInstance.behavior shouldBe ("TODO")
        }

        // to test the property `transaction`
        should("test transaction") {
            // uncomment below to test the property
            //modelInstance.transaction shouldBe ("TODO")
        }

    }
}
