/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.alogram.payrisk.v1.models.ScoresSuccessResponse
import com.alogram.payrisk.v1.models.ScoreRecord

class ScoresSuccessResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ScoresSuccessResponse
        //val modelInstance = ScoresSuccessResponse()

        // to test the property `scores` - Score records within the requested window.
        should("test scores") {
            // uncomment below to test the property
            //modelInstance.scores shouldBe ("TODO")
        }

        // to test the property `nextPageToken` - A token for retrieving the next page of results.
        should("test nextPageToken") {
            // uncomment below to test the property
            //modelInstance.nextPageToken shouldBe ("TODO")
        }

    }
}
