/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.alogram.payrisk.v1.models.ScoreRecord
import com.alogram.payrisk.v1.models.EntityIds
import com.alogram.payrisk.v1.models.FraudScore
import com.alogram.payrisk.v1.models.ReasonDetail
import com.alogram.payrisk.v1.models.RiskBreakdown

class ScoreRecordTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ScoreRecord
        //val modelInstance = ScoreRecord()

        // to test the property `assessmentId` - Universal decision identifier (for purchases, equals paymentIntentId).
        should("test assessmentId") {
            // uncomment below to test the property
            //modelInstance.assessmentId shouldBe ("TODO")
        }

        // to test the property `decisionAt` - RFC 3339 timestamp with timezone.
        should("test decisionAt") {
            // uncomment below to test the property
            //modelInstance.decisionAt shouldBe ("TODO")
        }

        // to test the property `decision` - The synchronous risk decision for a purchase.
        should("test decision") {
            // uncomment below to test the property
            //modelInstance.decision shouldBe ("TODO")
        }

        // to test the property `riskScore` - Fraud risk score (0.00 - 1.00).
        should("test riskScore") {
            // uncomment below to test the property
            //modelInstance.riskScore shouldBe ("TODO")
        }

        // to test the property `paymentIntentId` - Server-minted unique payment identifier.
        should("test paymentIntentId") {
            // uncomment below to test the property
            //modelInstance.paymentIntentId shouldBe ("TODO")
        }

        // to test the property `fraudScore`
        should("test fraudScore") {
            // uncomment below to test the property
            //modelInstance.fraudScore shouldBe ("TODO")
        }

        // to test the property `breakdown`
        should("test breakdown") {
            // uncomment below to test the property
            //modelInstance.breakdown shouldBe ("TODO")
        }

        // to test the property `reasons` - Structured reason details for the score.
        should("test reasons") {
            // uncomment below to test the property
            //modelInstance.reasons shouldBe ("TODO")
        }

        // to test the property `entities`
        should("test entities") {
            // uncomment below to test the property
            //modelInstance.entities shouldBe ("TODO")
        }

        // to test the property `amount` - Value of the purchase in the specified currency. Must be a positive number with up to two decimal places. 
        should("test amount") {
            // uncomment below to test the property
            //modelInstance.amount shouldBe ("TODO")
        }

        // to test the property `currency` - ISO 4217 currency code (e.g., 'USD').
        should("test currency") {
            // uncomment below to test the property
            //modelInstance.currency shouldBe ("TODO")
        }

    }
}
