/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.alogram.payrisk.v1.models.SignalsAccountVariant
import com.alogram.payrisk.v1.models.Account
import com.alogram.payrisk.v1.models.EntityIds

class SignalsAccountVariantTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SignalsAccountVariant
        //val modelInstance = SignalsAccountVariant()

        // to test the property `signalType` - Value for account signals.
        should("test signalType") {
            // uncomment below to test the property
            //modelInstance.signalType shouldBe ("TODO")
        }

        // to test the property `entities`
        should("test entities") {
            // uncomment below to test the property
            //modelInstance.entities shouldBe ("TODO")
        }

        // to test the property `account`
        should("test account") {
            // uncomment below to test the property
            //modelInstance.account shouldBe ("TODO")
        }

    }
}
