/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.alogram.payrisk.v1.models.SignalsRequest
import com.alogram.payrisk.v1.models.Account
import com.alogram.payrisk.v1.models.EntityIds
import com.alogram.payrisk.v1.models.Interaction
import com.alogram.payrisk.v1.models.SignalsAccountVariant
import com.alogram.payrisk.v1.models.SignalsInteractionVariant

class SignalsRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SignalsRequest
        //val modelInstance = SignalsRequest()

        // to test the property `signalType` - Value for interaction signals.
        should("test signalType") {
            // uncomment below to test the property
            //modelInstance.signalType shouldBe ("TODO")
        }

        // to test the property `entities`
        should("test entities") {
            // uncomment below to test the property
            //modelInstance.entities shouldBe ("TODO")
        }

        // to test the property `account`
        should("test account") {
            // uncomment below to test the property
            //modelInstance.account shouldBe ("TODO")
        }

        // to test the property `interactions` - One or more interactions associated with the signal.
        should("test interactions") {
            // uncomment below to test the property
            //modelInstance.interactions shouldBe ("TODO")
        }

    }
}
