/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.alogram.payrisk.v1.models.StoredCredentialContext
import com.alogram.payrisk.v1.models.PurchaseInitiatorEnum
import com.alogram.payrisk.v1.models.PurchaseSequenceEnum
import com.alogram.payrisk.v1.models.PurchaseUsageEnum

class StoredCredentialContextTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of StoredCredentialContext
        //val modelInstance = StoredCredentialContext()

        // to test the property `usage`
        should("test usage") {
            // uncomment below to test the property
            //modelInstance.usage shouldBe ("TODO")
        }

        // to test the property `sequence`
        should("test sequence") {
            // uncomment below to test the property
            //modelInstance.sequence shouldBe ("TODO")
        }

        // to test the property `initiator`
        should("test initiator") {
            // uncomment below to test the property
            //modelInstance.initiator shouldBe ("TODO")
        }

    }
}
