/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.alogram.payrisk.v1.models.ThreeDSData

class ThreeDSDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ThreeDSData
        //val modelInstance = ThreeDSData()

        // to test the property `version` - The version of the 3D Secure protocol used (e.g., '2.2.0').
        should("test version") {
            // uncomment below to test the property
            //modelInstance.version shouldBe ("TODO")
        }

        // to test the property `eci` - Electronic Commerce Indicator. Values indicate the outcome of 3D Secure authentication. 
        should("test eci") {
            // uncomment below to test the property
            //modelInstance.eci shouldBe ("TODO")
        }

        // to test the property `flow` - The flow of the 3D Secure authentication. 'frictionless' means no challenge was presented to the cardholder, 'challenge' means the cardholder was challenged. 
        should("test flow") {
            // uncomment below to test the property
            //modelInstance.flow shouldBe ("TODO")
        }

        // to test the property `liabilityShift` - Indicates whether liability for chargebacks has shifted to the issuer (true) or remains with the merchant (false). 
        should("test liabilityShift") {
            // uncomment below to test the property
            //modelInstance.liabilityShift shouldBe ("TODO")
        }

        // to test the property `cavvPresent` - Indicates whether the Cardholder Authentication Verification Value (CAVV) was present in the 3DS message. 
        should("test cavvPresent") {
            // uncomment below to test the property
            //modelInstance.cavvPresent shouldBe ("TODO")
        }

    }
}
