/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.alogram.payrisk.v1.models.Wallet
import com.alogram.payrisk.v1.models.PaymentWalletTypeEnum

class WalletTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Wallet
        //val modelInstance = Wallet()

        // to test the property `type` - Fixed to `wallet` for this schema.
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `walletType`
        should("test walletType") {
            // uncomment below to test the property
            //modelInstance.walletType shouldBe ("TODO")
        }

    }
}
