/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.alogram.payrisk.v1.api

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.alogram.payrisk.v1.api.PayriskApiClient
import com.alogram.payrisk.v1.models.AccountCheckRequest
import com.alogram.payrisk.v1.models.CheckRequest
import com.alogram.payrisk.v1.models.DecisionResponse
import com.alogram.payrisk.v1.models.KycCheckRequest
import com.alogram.payrisk.v1.models.PaymentEvent
import com.alogram.payrisk.v1.models.Problem
import com.alogram.payrisk.v1.models.ScoresSuccessResponse
import com.alogram.payrisk.v1.models.SignalsRequest

class PayriskApiClientTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PayriskApiClient
        //val apiInstance = PayriskApiClient()

        // to test accountRiskCheck
        should("test accountRiskCheck") {
            // uncomment below to test accountRiskCheck
            //val xIdempotencyKey : kotlin.String = xIdempotencyKey_example // kotlin.String | Unique Idempotency-Key sent in the POST request etc.
            //val accountCheckRequest : AccountCheckRequest =  // AccountCheckRequest | 
            //val xTraceId : kotlin.String = xTraceId_example // kotlin.String | Echoed or generated trace ID for tracking requests.
            //val result : DecisionResponse = apiInstance.accountRiskCheck(xIdempotencyKey, accountCheckRequest, xTraceId)
            //result shouldBe ("TODO")
        }

        // to test getFraudScores
        should("test getFraudScores") {
            // uncomment below to test getFraudScores
            //val tenantId : kotlin.String = tenantId_example // kotlin.String | 
            //val xTraceId : kotlin.String = xTraceId_example // kotlin.String | Echoed or generated trace ID for tracking requests.
            //val xIdempotencyKey : kotlin.String = xIdempotencyKey_example // kotlin.String | Unique Idempotency-Key sent in the GET request etc.
            //val startTime : kotlin.String = startTime_example // kotlin.String | 
            //val endTime : kotlin.String = endTime_example // kotlin.String | 
            //val pageSize : kotlin.Int = 56 // kotlin.Int | 
            //val pageToken : kotlin.String = pageToken_example // kotlin.String | 
            //val result : ScoresSuccessResponse = apiInstance.getFraudScores(tenantId, xTraceId, xIdempotencyKey, startTime, endTime, pageSize, pageToken)
            //result shouldBe ("TODO")
        }

        // to test healthCheck
        should("test healthCheck") {
            // uncomment below to test healthCheck
            //apiInstance.healthCheck()
        }

        // to test ingestPaymentEvent
        should("test ingestPaymentEvent") {
            // uncomment below to test ingestPaymentEvent
            //val xIdempotencyKey : kotlin.String = xIdempotencyKey_example // kotlin.String | Unique Idempotency-Key sent in the POST request etc.
            //val paymentEvent : PaymentEvent =  // PaymentEvent | 
            //val xTraceId : kotlin.String = xTraceId_example // kotlin.String | Echoed or generated trace ID for tracking requests.
            //apiInstance.ingestPaymentEvent(xIdempotencyKey, paymentEvent, xTraceId)
        }

        // to test ingestSignals
        should("test ingestSignals") {
            // uncomment below to test ingestSignals
            //val xIdempotencyKey : kotlin.String = xIdempotencyKey_example // kotlin.String | Unique Idempotency-Key sent in the POST request etc.
            //val signalsRequest : SignalsRequest =  // SignalsRequest | 
            //val xTraceId : kotlin.String = xTraceId_example // kotlin.String | Echoed or generated trace ID for tracking requests.
            //apiInstance.ingestSignals(xIdempotencyKey, signalsRequest, xTraceId)
        }

        // to test kycRiskCheck
        should("test kycRiskCheck") {
            // uncomment below to test kycRiskCheck
            //val xIdempotencyKey : kotlin.String = xIdempotencyKey_example // kotlin.String | Unique Idempotency-Key sent in the POST request etc.
            //val kycCheckRequest : KycCheckRequest =  // KycCheckRequest | 
            //val xTraceId : kotlin.String = xTraceId_example // kotlin.String | Echoed or generated trace ID for tracking requests.
            //val result : DecisionResponse = apiInstance.kycRiskCheck(xIdempotencyKey, kycCheckRequest, xTraceId)
            //result shouldBe ("TODO")
        }

        // to test riskCheck
        should("test riskCheck") {
            // uncomment below to test riskCheck
            //val xIdempotencyKey : kotlin.String = xIdempotencyKey_example // kotlin.String | Unique Idempotency-Key sent in the POST request etc.
            //val checkRequest : CheckRequest =  // CheckRequest | 
            //val xTraceId : kotlin.String = xTraceId_example // kotlin.String | Echoed or generated trace ID for tracking requests.
            //val result : DecisionResponse = apiInstance.riskCheck(xIdempotencyKey, checkRequest, xTraceId)
            //result shouldBe ("TODO")
        }

    }
}
